### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by vitaut** [cppformat/cppformat#103]
Currently the changes are tracked on the [GitHub Releases](https://github.com/cppformat/cppformat/releases) page which is pretty detailed, but including this information in the package can be beneficial.

**Comment by patlecat** [comment]
You could also run mantisBt and have it added as a service in github to generate and manage changes and changelogs.

**Comment by vitaut** [comment]
Thanks, but I kind of like it handcrafted =). Not much work anyway.
