### ISSUE TITLE
Update benchmark

### ISSUE THREAD

**Issue by vitaut** [cppformat/cppformat#106]
Follow [d-marc's suggestion](https://isocpp.org/blog/2015/02/release-of-cpp-format-1.0-a-small-safe-and-fast-formatting-library-for-c-vi) and try improving performance of the IOStreams version:

> I think it could help if the string literals with a length of one character would be replaced by character literals. Simply replace all occurrences of ":" by ':'. This avoids calling strlen() or some equivalent to figure out the length of the string all the time.

Also update Tinyformat to a newer version as there was some improvements there as well.

**Comment by vitaut** [comment]
Done.

**Comment by patlecat** [comment]
@vitaut So you only redone the tinyformat tests not the bloattest? And have you updated the data on the Readme too? Could you add the versions of the other 3rd party libs too please?

**Comment by vitaut** [comment]
Yes, I updated only speed tests, since bloat tests are relatively up-to-date. The README shows the new timings. I've just added the version information to the table if that's what you mean.
