### ISSUE TITLE
Use MSVC intrinsics for better performance

### ISSUE THREAD

**Issue by CarterLi** [cppformat/cppformat#115]
We [use compiler builtins on gcc](https://github.com/cppformat/cppformat/blob/master/format.h#L548)
[Similar functions](https://msdn.microsoft.com/zh-cn/library/fbxyd7zd(v=vs.100).aspx) exist for MSVC
Some implementations:
http://stackoverflow.com/questions/355967/how-to-use-msvc-intrinsics-to-get-the-equivalent-of-this-gcc-code
http://llvm.org/viewvc/llvm-project/libcxx/trunk/include/support/win32/support.h?view=markup#l124

**Comment by vitaut** [comment]
Yeah, this is on my TODO list, but I didn't have time to work on it yet. Thanks for the suggestion.
