### ISSUE TITLE
Alternative integer format

### ISSUE THREAD

**Issue by cobura2** [cppformat/cppformat#120]
I noted in the documentation that the format syntax is based on python. In python two forms of syntax are allowed for integer both "d" and "i". see following link

https://docs.python.org/2/library/stdtypes.html#string-formatting

This code gives an exception as "i" integer format is not allowed:

fmt::print("int: {0:d};  alternative int: {0:i};  hex: {0:x};  oct: {0:o}; bin: {0:b}", 42);

Should you allow the "i" format in a later release ?

**Comment by vitaut** [comment]
Thanks for the suggestions, but the format syntax is mostly based on [str.format](https://docs.python.org/2/library/string.html#formatstrings) where `d` is used for decimal integers. The one you refer to applies to the Python's interpolation operator `%` and is similar to `printf`. The C++ Format library already support "i" specifier in `fmt::printf`:

```c++
fmt::printf("%i", 42);
```

**Comment by cobura2** [comment]
Hi Victor

 

Thanks for the reply. I see now that the format syntax is very closely aligned with Python’s str.format function. To be honest I was looking at ways where I could maybe contribute to your open source project. I spent 4 hours looking at it yesterday and I couldn’t see any holes in it that I could quickly fill.

 

Could you let me know what the main reasons why someone would use fmt::printf over normal c library printf. Is it to get the exception handling support ?

 

Please let me know if there is anything I can help you with. My main programming language is C++ but lately I have been also programming in python

 

Thanks for your prompt reply.

 

Best regards

 

Andrew

**Comment by vitaut** [comment]
Hi Andrew,

It's great that you are interested in contributing to C++ Format.

> Could you let me know what the main reasons why someone would use fmt::printf over normal c library printf. Is it to get the exception handling support ?

`fmt::(s)printf` has several advantages over libc's `(s)printf`:

* Safety: libc's `printf` relies on varargs which are inherently unsafe while C++ Format uses variadic functions (emulated on pre-C++11). Safety issues in printf can be addressed with [\_\_attribute\_\_ ((format (printf, ...))](http://gcc.gnu.org/onlinedocs/gcc/Function-Attributes.html), but it is not portable and only works with literal strings while in practice format strings can be dynamic (esp. when localized).

* Extensibility: `fmt::printf` supports formatting of user defined types.

* Performance: `fmt::printf` is much faster on integer formatting. (It is currently slower on floating-point formatting, but I plan to address this soon.)

* Portability: [According to 0 A.D. developers](http://trac.wildfiregames.com/ticket/3011), `fmt::printf` is more portable than libc's printf. In particular, it provides consistent output across platforms and implements POSIX extensions for positional arguments that are not available in some `printf` implementations.

That said, `fmt::printf` is mostly there to simplify migration for the code that already uses system `printf`. `fmt::format`'s string syntax inherited from Python's `str.format` is more expressive and can be easily extended for custom types (although this is not used in the library yet).

> Please let me know if there is anything I can help you with. My main programming language is C++ but lately I have been also programming in python

I suggest choosing something you are interested in working on from [Issues](https://github.com/cppformat/cppformat/issues). For example, implementing custom streambuf in Issue #92 or replacing use of `BasicStringRef::c_str()` with `data()` and `size()` in #100. Feel free to ask if you have any questions.

Thanks,
Victor
