### ISSUE TITLE
can't clone format-benchmark - fails to find cppformat/sphinx_rtd_theme

### ISSUE THREAD

**Issue by mintyc** [cppformat/cppformat#123]
git clone --recursive https://github.com/cppformat/format-benchmark.git
fails at
'Clone of 'https://github.com/cppformat/sphinx_rtd_theme.git' into submodule path 'doc/sphinx_rtd_theme' failed'

Repo deleted and not found, so perhaps update to use cppformat lib from a few days after 1.0 when you had removed that sub-module.

Sorry I can't check it out to give you a pull request!

**Comment by vitaut** [comment]
Fixed in https://github.com/cppformat/format-benchmark/commit/4bbdc8bacef05a8f87320c67ec31b9c8188afef8. Thanks for catching this.
