### ISSUE TITLE
Support Java / Objective-C positional argument format?

### ISSUE THREAD

**Issue by timcloss** [cppformat/cppformat#126]
I'm currently i18-ing a cross-platform app that have native Java code, native Obj-C code, and a shared C++ layer. Our design has one set of localisation files (CSV files), which can be interpreted by any of these layers.

Java and Obj-C share the same sprintf format, with positional arguments, bar the fact that Obj-C uses '@' rather than 's' for the string identifier... easy to work around.

C++ is more of a problem, and I'm just about to look into it. I want to be able to load the same CSV files (which, where there are positional arguments, has them in Java format) and use them within C++ code.

Could cppformat support this? How easy would it be to convert Java's %1$s, %2$s etc. into something cppformat can use?

**Comment by vitaut** [comment]
C++ Format implements POSIX extension of `printf` for positional arguments as described [here](http://pubs.opengroup.org/onlinepubs/009695399/functions/fprintf.html) which is the same as what Java uses. For example:

```
  fmt::printf("%1$s, %2$s", "abc", "def");
```
