### ISSUE TITLE
Automate release procedure

### ISSUE THREAD

**Issue by vitaut** [cppformat/cppformat#127]
The release script should
- [x] Build the docs
- [x] Create source package
- [x] Convert changelog from reStructuredText to Markdown
- [x] Publish the release on github including changes from item 3 and package from item 2
- [ ] Publish new version on Biicode
- [ ] Update website

Also make sure that `breathe.css` is copied to output.

**Comment by patlecat** [comment]
Tell us more about it. How does it work? :)

**Comment by vitaut** [comment]
At this stage it works as follows:

![Python](http://imgs.xkcd.com/comics/python.png)

Haven't thought out the details yet.

**Comment by vitaut** [comment]
Also should probably do release preparation in a separate branch and squash all the ChangeLog update commits next time to avoid polluting the history.

**Comment by vitaut** [comment]
All done except the last two items. Migrated the last one to a separate issue and will update Biicode on request.
