### ISSUE TITLE
Enums as argument in fmt::sprintf throws fmt::FormatError

### ISSUE THREAD

**Issue by Naios** [cppformat/cppformat#131]
Rev: a037a829f

If i use an enum as argument with formatter %u, %i and %d in sprintf, fmt::FormatError is thrown because it isn't autoconverted to unsigned int.

Using msvc 12.

**Comment by vitaut** [comment]
Thanks for the bug report. Fixed in https://github.com/cppformat/cppformat/commit/5821aec7b933cf96a03a4b7853dd4b456f5b172e.

**Comment by Naios** [comment]
Thanks a lot for your fast fix :+1:
