### ISSUE TITLE
Broken clang build

### ISSUE THREAD

**Issue by Naios** [cppformat/cppformat#139]
https://api.travis-ci.org/jobs/54867976/log.txt

Probably caused by 275d1ab4231cbe804d5

>> [0m[1m/home/travis/build/TrinityCore/TrinityCore/dep/cppformat/format.h:779:15: [0m[0;1;30mnote: [0m
      candidate function[0m
  static yes &check(unsigned char);
[0;1;32m              ^
[0m[1m/home/travis/build/TrinityCore/TrinityCore/dep/cppformat/format.h:782:15: [0m[0;1;30mnote: [0m
      candidate function[0m
  static yes &check(int);

**Comment by vitaut** [comment]
Should be fixed in https://github.com/cppformat/cppformat/commit/bf8636c9596fbfddded3d0f5879abc7579c9f4dd. Also added a test case in https://github.com/cppformat/cppformat/commit/2adbfa4af7b9bcb437b4341bae06d9d8a766d6b2 to avoid such breakage in the future. Thanks!

**Comment by Naios** [comment]
I have to thank you ,-)
