### ISSUE TITLE
compilation error on msvc with FMT_EXCEPTIONS=0

### ISSUE THREAD

**Issue by sbrednikhin** [cppformat/cppformat#144]
error C4716: '`anonymous namespace'::PrecisionHandler::visit_unhandled_arg' : must return a value	..\cppformat\format.cc	334
error C4716: '`anonymous namespace'::WidthHandler::visit_unhandled_arg' : must return a value	..\cppformat\format.cc	312

FMT_NO_RETURN works wrong

  FMT_NORETURN
  unsigned visit_unhandled_arg() {
    FMT_THROW(fmt::FormatError("width is not integer"));
  }

Maybe it's better to return something instead?

  FMT_NORETURN
  unsigned visit_unhandled_arg() {
    FMT_THROW(fmt::FormatError("width is not integer"));
    return 0
  }

Or make some void method?

FMT_NORETURN 
void visit_unhandled_arg_noret() {
  FMT_THROW(fmt::FormatError("width is not integer"));
} 
unsigned visit_unhandled_arg() {
    visit_unhandled_arg_noret();
}

**Comment by vitaut** [comment]
Should be fixed in https://github.com/cppformat/cppformat/commit/66915785ddc76802a26745cce6cfb9c119197750. Thanks for reporting!
