### ISSUE TITLE
MSVC 12: Warnings

### ISSUE THREAD

**Issue by Naios** [cppformat/cppformat#145]
On: 3a5573ac6e17cdd5c36a7cc2bf1a8cc8abfa20ce

```
2>c:\source\trinitycore335\dep\cppformat\format.h(2711): warning C4789: buffer 'array' of size 48 bytes will be overrun; 4 bytes will be written starting at offset 48
2>c:\source\trinitycore335\dep\cppformat\format.h(2711): warning C4789: buffer 'array' of size 24 bytes will be overrun; 4 bytes will be written starting at offset 24
2>c:\source\trinitycore335\dep\cppformat\format.h(2711): warning C4789: buffer 'array' of size 72 bytes will be overrun; 4 bytes will be written starting at offset 72
2>c:\source\trinitycore335\dep\cppformat\format.h(2711): warning C4789: buffer 'array' of size 72 bytes will be overrun; 4 bytes will be written starting at offset 72
2>c:\source\trinitycore335\dep\cppformat\format.h(2711): warning C4789: buffer 'array' of size 48 bytes will be overrun; 4 bytes will be written starting at offset 48
2>c:\source\trinitycore335\dep\cppformat\format.h(2711): warning C4789: buffer 'array' of size 72 bytes will be overrun; 4 bytes will be written starting at offset 72
2>c:\source\trinitycore335\dep\cppformat\format.h(2711): warning C4789: buffer 'array' of size 24 bytes will be overrun; 4 bytes will be written starting at offset 24
2>c:\source\trinitycore335\dep\cppformat\format.h(2711): warning C4789: buffer 'array' of size 96 bytes will be overrun; 4 bytes will be written starting at offset 96
2>c:\source\trinitycore335\dep\cppformat\format.h(2711): warning C4789: buffer 'array' of size 24 bytes will be overrun; 4 bytes will be written starting at offset 24
2>c:\source\trinitycore335\dep\cppformat\format.h(2711): warning C4789: buffer 'array' of size 72 bytes will be overrun; 4 bytes will be written starting at offset 72
2>c:\source\trinitycore335\dep\cppformat\format.h(2711): warning C4789: buffer 'array' of size 48 bytes will be overrun; 4 bytes will be written starting at offset 48
2>c:\source\trinitycore335\dep\cppformat\format.h(2711): warning C4789: buffer 'array' of size 96 bytes will be overrun; 4 bytes will be written starting at offset 96
```

**Comment by vitaut** [comment]
Thanks for reporting. Could you by any chance give an example that triggers the warnings?

**Comment by amc522** [comment]
I get these same warnings when compiling just compiling format.cc. Currently compiling with Visual Studio (12) 2013. I only get these errors when compiling for 64bit with /W4. I believe it has to do with the ```#define FMT_VARIADIC_``` definition. I get warnings about the constant expression being evaluated
```if (sizeof...(Args) > fmt::ArgList::MAX_PACKED_ARGS)```
If the compiler does not remove the code inside that if block, then this line:
```array[sizeof...(Args)].type = Arg::NONE;```
will still be evaluated even though it will never be hit. That statement would cause a warning about going out of the array bounds.

So I dont think there is any bad or dangerous code. The compiler is reading more into it than it has to. I wrapped all the ```FMT_VARIADIC``` declarations in the following.

```
#ifdef _MSC_VER
# pragma warning(push)
# pragma warning(disable: 4127)
# pragma warning(disable: 4789)
#endif
...
#ifdef _MSC_VER
# pragma warning(pop)
#endif
```

I dont know what the right solution is though.

**Comment by Naios** [comment]
Naios/TrinityCore@f218d80b9c8aede7a361203b7fb2fbc743681831 produces a lot of warnings with the latest cppformat (rev 3a5573ac6e17cdd5c36a7cc2bf1a8cc8abfa20ce).

Probably every log message which is calling fmt::sprintf produces an error for example:

``` c++
TC_LOG_INFO("sql.updates", "Updating %s database...", DBUpdater<T>::GetTableName().c_str());
```

**Comment by vitaut** [comment]
I think https://github.com/cppformat/cppformat/commit/d2387999ece1117527d93f947e9cc3436c1881a3 should fix these warnings. Unfortunately I couldn't verify the fix as the warnings are not reported in the [AppVeyor build](https://ci.appveyor.com/project/vitaut/cppformat/build/1.0.924/job/vr0xorhndjg7v9nh) even with /W4. Thanks @amc522 and @Naios.

**Comment by amc522** [comment]
Yep, that fixed the warnings. Just tested with x86 and x64 in Visual Studio 2013 and the warnings no longer appear. Thanks!

**Comment by vitaut** [comment]
Thank you for the confirmation, @amc522.
