### ISSUE TITLE
no installation target in CMakeLists

### ISSUE THREAD

**Issue by kain88-de** [cppformat/cppformat#151]
Is there a reason why you don't have an installation target in the CMakeLists.txt? I currently use a dynamic version of this library in a project and I have to send colleagues patches so that they can use cmake to build and install the dynamic library on their system.

**Comment by vitaut** [comment]
The `install` target is created by CMake automatically, so the following works (at least in version 1.1.0):

```
$ cmake .
$ make
$ sudo make install
```

**Comment by kain88-de** [comment]
hm weird it didn't want to to this in the morning. Maybe I had some old cmake config. Thanks for the quick answer though
