### ISSUE TITLE
std::min is broken if FMT_HEADER_ONLY is defined.

### ISSUE THREAD

**Issue by DevO2012** [cppformat/cppformat#152]
Solution is to put flowing lines just before windows include.

    #include <windows.h>
    #define WIN32_LEAN_AND_MEAN
    #define NOMINMAX

**Comment by vitaut** [comment]
Thanks for the bug report. I couldn't find any reference to `std::min` in C++ Format other than in tests which don't use `FMT_HEADER_ONLY`. Could you post the full error that you get?

**Comment by DevO2012** [comment]
The problem is that windows.h will define min and max macros.
It will also include a lot of other garbage that usually nobody need.
This will break any usage of std::min and std::max in later code.
I have added pull request about this.

**Comment by VimParrotCoop** [comment]
you can just write int a = (std::min)(10, 20); and min max macros will not work and you don't need NOMINMAX

**Comment by newnon** [comment]
you can just write int a = (std::min)(10, 20); and min max macros will not work and you don't need NOMINMAX

**Comment by vitaut** [comment]
This is  a well-known problem with Windows headers and unfortunately I don't see a good way to address this without potentially breaking user code (which can happen if we unconditionally define `NOMINMAX`) that also includes `windows.h`. Possible solutions:

* Use the default non-header-only configuration
* Define `NOMINMAX` before including `format.h` or on a project level

@DevO2012 Will it work for you?

**Comment by DevO2012** [comment]
Yes I know that I can write (std::min)(10, 20) but only in my code not in other libraries that use std::min and std::max.

>  I don't see a good way to address this without potentially breaking user code (which can happen if we unconditionally define NOMINMAX) that also includes windows.h
Can you please elaborate how this can break user code ?
Do you mean that a lost of users still use preprocessor based  min and max, this would be big surprise for me ? 

> Define NOMINMAX before including format.h or on a project level
Ok this seems to be the most safe solution :)

**Comment by vitaut** [comment]
> Can you please elaborate how this can break user code ?

It can happen if `windows.h` is included directly or via another header after including `format.h` and then a `min` or `max` macro is used, possibly by code in another header (this can even be C code):

#include <format.h>
#include <windows.h> // can be included in another header, possibly C
max(1, 2); // same as above

> Do you mean that a lost of users still use preprocessor based min and max, this would be big surprise for me ?

I hope noone is using `min` and `max` macros, but I don't want to break their code if they do. Although they probably deserve their code to be broken =).

> Ok this seems to be the most safe solution :)

Cool, I'm closing this issue then, but if you have any ideas on how to improve the situation feel free to reopen it.

**Comment by DevO2012** [comment]
How about this solution ?

# define WIN32_LEAN_AND_MEAN
# define NOMINMAX
# include <windows.h>
# undef  NOMINMAX
# undef  WIN32_LEAN_AND_MEAN

**Comment by vitaut** [comment]
I've implemented something similar in https://github.com/cppformat/cppformat/commit/67ce39425636e329688f140b8c60f7d6adf6ee4d. Unfortunately it may still break if someone uses `min`/`max` macros because `NOMINMAX` only applies to the first include of `windows.h`. But it's probably a lesser evil compared to breaking `std::min/max` and it can be disabled by defining `FMT_WIN_MINMAX`. In any case this only applies to the header-only configuration so it's not that important. Thanks @DevO2012.
