### ISSUE TITLE
Are there plans on adding Ubuntu packages for this?

### ISSUE THREAD

**Issue by danijar** [cppformat/cppformat#155]

**Comment by vitaut** [comment]
It shouldn't be too difficult to make a [`.deb` package with CMake](http://www.cmake.org/Wiki/CMake:CPackPackageGenerators#DEB_.28UNIX_only.29), but I don't have immediate plans to do this. Pull requests are welcome!

**Comment by vitaut** [comment]
Here's a Debian ITP for C++ Format kindly proposed by Eugene V. Lyubimkin: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785408

**Comment by danijar** [comment]
Thanks for pointing me to it.

**Comment by vitaut** [comment]
Thanks to Eugene, C++ Format is now in Debian: https://packages.debian.org/source/sid/cppformat. `.dep` packages can be downloaded and installed in Ubuntu as well.

**Comment by vitaut** [comment]
C++ Format is in Ubuntu repos now: http://zverovich.net/2015/10/26/cppformat-packages-for-linux-and-osx.html
