### ISSUE TITLE
Installing `cppformat` using homebrew (macos)

### ISSUE THREAD

**Issue by ortho** [cppformat/cppformat#157]
Now. It's possible to install your library using [homebrew](http://brew.sh)
```
brew install cppformat
```

It will be great to describe this possibility in documentation.

Thanks you for the library!

**Comment by vitaut** [comment]
Thanks for adding support for C++ Format to Homebrew, much appreciated! I've added a small section to [Usage](https://github.com/cppformat/cppformat/blob/master/doc/usage.rst#homebrew). Please let me know if you want to add or change anything there.

**Comment by skgbanga** [comment]
@ortho @vitaut I did `brew install fmt` as described in the usage section, but I still had to add the library path "/usr/local/Cellar/fmt/4.0.0/lib/libfmt.a" to my compile command.

I was wondering if this is normal?

**Comment by vitaut** [comment]
As far as I can see `brew install fmt` creates a symlink in `/usr/local/lib`:

```
lrwxr-xr-x  1 viz  staff  32 Oct  8 14:24 /usr/local/lib/libfmt.a -> ../Cellar/fmt/4.0.0/lib/libfmt.a
```

Since this directory is on the library search path, you can just do

```
$ c++ -lfmt ...
```

**Comment by skgbanga** [comment]
You are right. I didn't notice it. Thanks for taking a look.
