### ISSUE TITLE
Minor Issue: Compiler warnings about unused parameter

### ISSUE THREAD

**Issue by fmatthew5876** [cppformat/cppformat#158]
Trying to compile cppformat in my project produces a compiler warning about an unused parameter.

Below is a quick fix. Alternatively you can do (void)values; in the function body.

    diff --git a/format.h b/format.h
    index 9e68867..51ec420 100644
    --- a/format.h
    +++ b/format.h
    @@ -1484,7 +1484,7 @@ inline void set_types(Value *, const Args & ...) {
    }
 
     template <typename Char, typename Value>
    -inline void store_args(Value *values) {}
    +inline void store_args(Value *) {}
 
     template <typename Char, typename Arg, typename T, typename... Args>
     inline void store_args(Arg *args, const T &arg, const Args & ... tail) {

**Comment by vitaut** [comment]
Should be fixed in https://github.com/cppformat/cppformat/commit/c15072294515fd2faad1194d2117c56db4687f46. Thanks!
