### ISSUE TITLE
Inconsistent definition warning: fmt::internal::BasicData<>

### ISSUE THREAD

**Issue by LevskiWeng** [cppformat/cppformat#163]
Line 1066 of format.cc (template class fmt::internal::BasicData<>)
Line 603 of format.h (template struct fmt::internal::BasicData<>)

Through it could be compiled, but VS2012 throws a warning.

What do you think?

**Comment by vitaut** [comment]
Good catch. Fixed in https://github.com/cppformat/cppformat/commit/9ca1ce293e46a5dec85d023895410be5c76c0aa8. Thanks!
