### ISSUE TITLE
has cppformat has compile-time checking support like printf or sprintf?

### ISSUE THREAD

**Issue by zjay1987** [cppformat/cppformat#166]
for example, the follow statment

printf("hello, %s\n", 1);

will fire an compiler warning, but cppformat library does not

**Comment by vitaut** [comment]
You can use a simple trick described in https://github.com/cppformat/cppformat/issues/62#issuecomment-77490707 to get similar compile-time checking with C++ Format.

**Comment by vitaut** [comment]
Compile-time format string checks are now available: http://zverovich.net/2017/11/05/compile-time-format-strings.html
