### ISSUE TITLE
Clang Warnings (with -W -Wall -Werror)

### ISSUE THREAD

**Issue by cubicool** [cppformat/cppformat#175]
The no-op, internal strerror_r ends up being unused when compiling with Clang on Linux with all error-reporting and pedantacism enabled. The following error is generated:

    cppformat/format.cc:98:37: error: unused function 'strerror_r' [-Werror,-Wunused-function]
    static inline fmt::internal::None<> strerror_r(int, char *, ...) {
                                    ^
    1 error generated.

I found the following link that helps explain the situation somewhat: http://zverovich.net/2015/03/13/reliable-detection-of-strerror-variants.html

For now I'm simply adding -Wno-unused-function, but seeing as I use cppformat like a fiend, it'd be nice to have it fixed in the source. I will submit a PR if desired.

**Comment by vitaut** [comment]
Fixed in https://github.com/cppformat/cppformat/commit/63f6c104495777de70a27f838caa19fd0590a8aa. Thanks!
