### ISSUE TITLE
Can't print a lambda

### ISSUE THREAD

**Issue by gnzlbg** [cppformat/cppformat#176]
That the following fails is obvious:

```c++
 fmt::print("[&](auto&& i) { return 0; }");
```

it throws a `fmt::FormatError: invalid format string`. 

This prevents me from using cppformat anywhere I might want to print C++ code by expanding it to a string literal using a macro parameter: `#define PRINT_CODE(A) fmt::print(#A)`.

Is there a way around this?

Right now `{` can be escaped with `{{`. I think if one could delimit a part of the string to ignore format parameters this would work, e.g., using `{!{!`/`!}!}` or similar (is there a standard for this?) to write: 
`#define EXPAND(A) fmt::print("{!{!" #A "!}!}")`.

**Comment by vitaut** [comment]
Why not pass the string as an argument? This will effectively be the same as ignoring the arguments in it with delimiters:

```c++
fmt::print("{}", "[&](auto&& i) { return 0; }");
```

**Comment by gnzlbg** [comment]
> Why not pass the string as an argument? This will effectively be the same as ignoring the arguments in it with delimiters:

Thanks, what a `duh` moment :D 

This solves it, I was kind of relying on string literal concatenation for performance but the performance in this case should be the same.

**Comment by vitaut** [comment]
Glad that it worked for you =). The performance should probably be comparable or even better as the arguments are not parsed.
