### ISSUE TITLE
(patch) out-of-tree build support for documentation

### ISSUE THREAD

**Issue by jackyf** [cppformat/cppformat#177]
https://sources.debian.net/src/cppformat/1.1.0%2Bds-3/debian/patches/0004-doc-cmakelists-out-of-tree-build-support.patch/

**Comment by vitaut** [comment]
Out-of-tree documentation build should be fixed in https://github.com/cppformat/cppformat/commit/dd6a3bbc7c86256fbaeaa83683a90917b61ae1b0. Thanks!
