### ISSUE TITLE
(patch) proposal for less generic names and paths of artifacts

### ISSUE THREAD

**Issue by jackyf** [cppformat/cppformat#178]
(1/2) https://sources.debian.net/src/cppformat/1.1.0%2Bds-3/debian/patches/0006-cmakelists-install-format.h-to-prefix-include-cppfor.patch/

(2/2) https://sources.debian.net/src/cppformat/1.1.0%2Bds-3/debian/patches/0008-cmakelists-name-static-library-cppformat.a-not-forma.patch/

**Comment by vitaut** [comment]
Merged with minor modifications in https://github.com/cppformat/cppformat/commit/b88a17ad9e044df174764d482b966765fe18babc and https://github.com/cppformat/cppformat/commit/958299dd7ff973fde3b1675a95e547bbd5b6c7d3. Thanks!
