### ISSUE TITLE
(patch) unit test portability improvements

### ISSUE THREAD

**Issue by jackyf** [cppformat/cppformat#179]
(1/3) https://sources.debian.net/src/cppformat/1.1.0%2Bds-3/debian/patches/0009-test-format-test-FormatIntTest-FormatDec-don-t-assum.patch/

(2/3) https://sources.debian.net/src/cppformat/1.1.0%2Bds-3/debian/patches/0010-test-compile-death-tests-only-when-GTest-provides-th.patch/

(3/3) https://sources.debian.net/src/cppformat/1.1.0%2Bds-3/debian/patches/0011-test-gtest-extra-test-FileTest-ReadError-WriteError-.patch/

**Comment by vitaut** [comment]
@jackyf Thanks for the patches. Regarding the last one, I think POSIX allows this:

[pipe](http://pubs.opengroup.org/onlinepubs/009695399/functions/pipe.html):
> A process has the pipe open for reading (correspondingly writing) if it has a file descriptor open that refers to the read end, fildes\[0] (write end, fildes\[1]).

[read](http://pubs.opengroup.org/onlinepubs/009695399/functions/read.html):

> [EBADF]
> The fildes argument is not a valid file descriptor open for reading.

Does it cause a test failure on some platform?

**Comment by vitaut** [comment]
My bad, I see you mention this in the commit message:

> Those unit tests actually fail on kfreebsd-* architectures: ReadError hangs and WriteError throws.
