### ISSUE TITLE
long double formatting unit test failure on powerpc architecture

### ISSUE THREAD

**Issue by jackyf** [cppformat/cppformat#180]
From the unit test run [1]:

----------------------8<-----------------------
[ RUN      ] FormatterTest.FormatLongDouble
/«BUILDDIR»/cppformat-1.1.0+ds/test/format-test.cc:1166: Failure
Value of: format("{0:+010.4g}", 392.65l)
  Actual: "+0000392.7"
Expected: "+0000392.6"
[  FAILED  ] FormatterTest.FormatLongDouble (0 ms)
---------------------->8-----------------------

I don't know whether this is an issue of flags or a compiler or the architecture or the test or the implementation. Please have a look.

[1] https://buildd.debian.org/status/fetch.php?pkg=cppformat&arch=powerpc&ver=1.1.0%2Bds-3&stamp=1434716610

**Comment by vitaut** [comment]
Should be fixed in https://github.com/cppformat/cppformat/commit/948317b6dd668b137a199e560ddbcd0109dda31c. Thanks for reporting.
