### ISSUE TITLE
Support for ranges

### ISSUE THREAD

**Issue by gnzlbg** [cppformat/cppformat#181]
Add support for printing ranges. Ideally:

```c++
std::initializer_list<int> a = {0, 2, 3, 4};
print("range: \"{r{}, }\"\n", a);
print("range: \"{r{}| }\"\n", a);
std::initializer_list<std::initializer_list<int>> a = { {0, 1}, {2, 3}, {4}};
print("range: \"{r{r{}, }| }\"\n", a);
```

would print 

```shell
range "0, 2, 3, 4"
range "0 | 2 | 3 | 4"
range "0, 1 | 2, 3 | 4"
```

This would require a new format specifier, e.g. `r`, followed by a format specifier for the range element and a separator string: `r{}sep`. Note that `r{r{}sep0}sep1` allows dealing with ranges of ranges.
A definition of `Range`, e.g., anything that can be called with non-member `begin` and `end`.

**Comment by vitaut** [comment]
Interesting idea. It should be possible to do via an extension mechanism:

```c++
#include <initializer_list>
#include "format.h"

namespace fmt {
template <typename Char, typename T>
void format(fmt::BasicFormatter<Char> &f, const Char *&format_str,
            std::initializer_list<T> values) {
  fmt::BasicWriter<Char> &writer = f.writer();
  for (const auto &value: values)
    writer << value;
}
}

int main() {
  std::initializer_list<int> a = {0, 2, 3, 4};
  fmt::print("range: \"{}\"\n", a);
}
```

This prints `range: "0234"` without any separators, but it is possible to parse the format string and write in the format you suggest.

**Comment by gnzlbg** [comment]
Cool I'll give it a try!

**Comment by vitaut** [comment]
Looks like this feature can be implemented on top of existing API without changes to the core library, so I'm going to close this. Feel free to reopen if this is not the case.
