### ISSUE TITLE
Support format string with streaming operators?

### ISSUE THREAD

**Issue by skebanga** [cppformat/cppformat#184]
`boost::format` allows you to specify a printf style format string, and then stream arguments with the `%` operator

    boost::format formatter("hello %s");
    formatter % "world";

    std::cout << formatter.str() << '\n';

Does `cppformat` support this?
If not, are there plans to support this?

**Comment by vitaut** [comment]
No. Like `printf`, C++ Format functions require all arguments be passed at once:

```c++
std::cout << fmt::format("hello {}", "world") << '\n';
```

This way there is no need to worry about the arguments' lifetimes and the implementation can be much more efficient.

It might be possible to construct `ArgList` incrementally and pass it to a formatting function, but it will rely on internal APIs and I wouldn't recommend it.
