### ISSUE TITLE
Argument shadowing and Clang pedantic support

### ISSUE THREAD

**Issue by rpopescu** [cppformat/cppformat#190]
Hi,

Pedantic warnings do not work on Clang (cmake 3.2.3, OSX 10.10.4, Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)).

I've made some changes to the main CMakeLists.txt to support that, and also fixed the shadowing warnings that come up with FMT_PEDANTIC set to ON.

I'm issuing a pull request now.

**Comment by vitaut** [comment]
Good catch, thanks! Just one small comment in #190.
