### ISSUE TITLE
mutiple x64 warnings about loss of data under VS2013

### ISSUE THREAD

**Issue by gabime** [cppformat/cppformat#194]
format.cc(636): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
format.cc(642): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
format.cc(656): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data
format.cc(661): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data

**Comment by vitaut** [comment]
Fixed in https://github.com/cppformat/cppformat/commit/c3ba615c653ca61502ddfef6379482b17921f543. Thanks!
