### ISSUE TITLE
std::ostringstream vs. fmt::MemoryWriter for simple string concatation

### ISSUE THREAD

**Issue by mdickie** [cppformat/cppformat#195]
I would like to know if there are any notable differences in speed.

**Comment by vitaut** [comment]
I don't have any specific numbers, but with `fmt::MemoryWriter` you can avoid dynamic memory allocation if the resulting string size is less than `INLINE_BUFFER_SIZE` which is currently set to 500. You can also avoid construction of `std::string` and access the buffer directly. On integer formatting, `MemoryWriter` is about 8 times faster than `std::ostringstream` (http://zverovich.net/2013/09/07/integer-to-string-conversion-in-cplusplus.html), but on string formatting the difference is likely to be smaller.
