### ISSUE TITLE
Safer printing for char arrays

### ISSUE THREAD

**Issue by Naav** [cppformat/cppformat#203]
**Some background:** I work with systems that expose strings as fixed-size `char` arrays. These strings are not necessarily null-terminated.

Consider the following piece of code:

    char buf[5] = { 'H', 'e', 'l', 'l', 'o' };

    fmt::MemoryWriter w;
    w.write("{}", buf);

This will result in Undefined Behavior (and possibly a segfault), as `write` treats `buf` as a `char*`, and hence keeps reading past end of `buf` until the first `\0` is found.

That's understandable, and the fix is easy enough:

    char buf[5] = { 'H', 'e', 'l', 'l', 'o' };

    fmt::MemoryWriter w;
    w.write("{:.{}}", buf, sizeof(buf));

But, *in this precise case*, the size of `buf` is readily available to the compiler, it would be nice if cppformat could deduce (by default) the maximum length of `buf` without requiring the user to specify a precision.

Such a feature would allow one to use the first code snippet without UB: cppformat would deduce `buf` as `char[5]` instead of `char*`, and pick a default precision of 5 for that argument, therefore just printing `Hello`, and nothing else.

**Comment by newnon** [comment]
char buff[255];
strcpy(buff, "test");
w.write("{}", buf);
what should writer do?

**Comment by Naav** [comment]
Not an issue, as `strcpy` copies the null terminator of `"test"`.

**Comment by vitaut** [comment]
This is an interesting idea, but I have some concerns:

1. This will only work with arrays and, if implemented, will introduce inconsistent behavior with pointers:

  ```c++
char buf[5] = { 'H', 'e', 'l', 'l', 'o' };
char *buf2 = buf;
fmt::MemoryWriter w;
w.write("{}", buf); // OK
w.write("{}", buf2); // UB
```

  While one may argue that it is somewhat safer then the current situation, I think that allowing one case and not the other might cause problems as it is too easy to pass a pointer instead of an array. For this reason, I'd prefer to catch the first case and reject it at compile time if possible instead of allowing it.

2. Implementing this may introduce some overhead for a much more common case of passing null-terminated strings.

Instead, I'd recommend using a function to construct a `StringRef` from a buffer, e.g.

```c++
template <std::size_t SIZE>
fmt::StringRef str(const char (&array)[SIZE]) {
  return fmt::StringRef(array, SIZE);
}

// Usage:
char buf[5] = { 'H', 'e', 'l', 'l', 'o' };
fmt::MemoryWriter w;
w.write("{}", str(buf));
```

Will this work for you?

**Comment by Naav** [comment]
> Instead, I'd recommend using a function to construct a StringRef from a buffer

IMO that *alone* is a very minor improvement over the current situation, as it still requires the user to think about the possible buffer overrun.

> For this reason, I'd prefer to catch the first case and reject it at compile time if possible instead of allowing it.

That seems very reasonable indeed, and combined with your other suggestion would make a good solution.

**Comment by vitaut** [comment]
@Naav Thanks for the feedback. The first part can be implemented already on top of existing interface and doesn't need anything from the library. The second part needs some investigation and changes to handling of string arguments. I can look into it, but it may take some time. Patches are very welcome too =).

**Comment by vitaut** [comment]
It is possible to check for null termination at compile time in C++11:

```c++
template <std::size_t N>
constexpr bool is_null_terminated(const char (&arr)[N]) {
  return !arr[N - 1];
}

constexpr char str[] = {'f', 'o', 'o'};
static_assert(is_null_terminated(str), "not null-terminated");
```

However, this cannot be directly applied to formatting functions because they are not `constexpr`.

So, I'm going to close this issue for now but if you have any ideas on how to implement this check, feel free to reopen.
