### ISSUE TITLE
Allow non-iostream builds?

### ISSUE THREAD

**Issue by JodiTheTigger** [cppformat/cppformat#205]
Hello,

would it be possible to make it so that I can use the format.cc/h library without it referencing any of the `*stream` headers/libraries?

I quickly hacked the files removing any reference to istream/ostream/sstream and it _seemed_ to build fine (g++ 5.2.0). So it seems like an easy do.

**Comment by vitaut** [comment]
Hi,
It should be pretty straightforward to do by conditionally compiling a few parts using iostreams, but could you give some details why you need this?

**Comment by JodiTheTigger** [comment]
Just a personal hatred for the entire stream system and API, both from a performance, and a readability perspective. 

Your library seems quite nice, since I'm not a fan of the printf system either. It would be a shame for it to be saddled by the streams ogre :-)

**Comment by vitaut** [comment]
Not a big fan of IOStreams myself, but I'd rather not clutter the code with more `#ifdef`s if this doesn't give substantial practical benefit. The library doesn't use IOStreams internally, only provides support for user-defined types that have overloaded `operator<<` which is entirely optional. Conditionally compiling this part won't improve the performance, but will slightly degrade readability.

**Comment by JodiTheTigger** [comment]
No problem.

If #ifdefs are too bothersome, then just put the stream functions into seperate files and make using streams (or disabling them) optional in the cmake file then.

**Comment by JodiTheTigger** [comment]
Whoops, just realised you're aiming for a 2 file library, so splitting the functions into their own files wouldn't work.

Which makes me ask why you are bothered by another #if*? considering you have 38 in the header file and 15 in the cc.

Noting importance, I'm also concerned with compile time. Include a stream header in a project DOES impacts compile time (although I admit only on mechanical HDDs, I compile on an SSD and it only increases build time by 2.5%)

**Comment by JodiTheTigger** [comment]
Anyway, I can do a pull request if you want.

**Comment by Spartan322** [comment]
Isn't removing the IOStream support unnecessary anyway, seems like its removal only takes out a relatively helpful feature, for a gain of near nothing.

**Comment by vitaut** [comment]
> Which makes me ask why you are bothered by another #if*? considering you have 38 in the header file and 15 in the cc.

I wish I could kill them =).

Anyway, if you feel strongly about not using iostreams, please do submit a PR.

**Comment by Spartan322** [comment]
If I'm allowed to ask, I'd like to know why the IOStreams are such a thing to worry about here, it seems close to little point in providing a removal of the streams, even if they are rather...well, eh, but is there really a benefit to doing this?

**Comment by vitaut** [comment]
@Spartan322 I'm somewhat skeptical myself as to practical benefit of this. 2.5% reduction in compile time doesn't sound like a big gain.

**Comment by JodiTheTigger** [comment]
Pull request as Issue #208.
