### ISSUE TITLE
The documentation is wider on small devices than on medium

### ISSUE THREAD

**Issue by dean0x7d** [cppformat/cppformat#210]
This is related to [Bootstrap's grid options](http://getbootstrap.com/css/#grid-options), so I'm using their definitions: a small device is ≥768px, medium ≥992px and large ≥1200px.

Take a [documentation page](http://cppformat.github.io/dev/api.html) and change the width of your browser window. Once you go below 992 pixels, the main content becomes wider rather than narrower. Medium is set to 8 columns and small to 12 columns.

Also, the navbar search box is strangely displaced in the medium view, but aligned in small and large.

**Comment by vitaut** [comment]
Good catch, thanks! Should be fixed in https://github.com/cppformat/cppformat/commit/caa8f76a88f644881b73d944ad73afeab7e2dabe and [online](http://cppformat.github.io/dev/).
