### ISSUE TITLE
MemoryBuffer::free() conflicts.

### ISSUE THREAD

**Issue by FrankStain** [cppformat/cppformat#211]
https://github.com/cppformat/cppformat/blob/master/format.h#L462

Using MS Visual Studio project with turned on memory leaks monitoring its unable to compile `format.h` cuz `free()` now becomes a macro `_free_dbg( p, _NORMAL_BLOCK )`.

Suggest to rename this method into `free_buffer()`.

Reproducing steps:

1- Modify `format.h` like that:
Was:
```.cpp
#ifndef FMT_FORMAT_H_
#define FMT_FORMAT_H_

#include <stdint.h>
```
Now:
```.cpp
#ifndef FMT_FORMAT_H_
#define FMT_FORMAT_H_

#define _CRTDBG_MAP_ALLOC
#include <crtdbg.h>

#include <stdint.h>
```

2- Try to compile `format.cc` using MS Visual Studio 2013+ (2015 used).
It will be failed with next messages:
```
format.h(465): warning C4003: not enough actual parameters for macro 'free'
format.h(475): warning C4003: not enough actual parameters for macro 'free'
format.h(504): warning C4003: not enough actual parameters for macro 'free'
format.h(465): error C2059: syntax error: ','
```

**Comment by vitaut** [comment]
Oh my, MSVC is a mess. Fixed in https://github.com/cppformat/cppformat/commit/77b32006a3cdfb6d4a8154cb1a92f23602660207, thanks!
