### ISSUE TITLE
Specify width as an argument as opposed to hard coding it in the format string.

### ISSUE THREAD

**Issue by JodiTheTigger** [cppformat/cppformat#219]
I have to do:
```cpp
auto my_string = fmt::format("{:80}", some_text);
```
but what I _want_ to do is:
```cpp
auto my_string = fmt::format("{:*}", some_text, 80);
```
normal printf has this capability.
http://www.cplusplus.com/reference/cstdio/printf/ (look under the width section)

1) Is it possible to do this with cppformat now?
2) If not, could it be added as a feature?

**Comment by vitaut** [comment]
Yes, it is possible to do:

```c++
  auto my_string = fmt::format("{:{}}", some_text, 80);
```
