### ISSUE TITLE
Throwing printf("%p", "cstring") is problematic

### ISSUE THREAD

**Issue by LarsGullik** [cppformat/cppformat#223]
When moving an application from using standard varargs and printf formatting to
cppformat the throwing printf("%p", "cstring") is problematic and a source for bugs.
This since (on most platforms?), standard usage of ("%p", "cstring), will not throw
but just print the pointer value as if an explict cast to void const * where there.

It seems easy to add support for this to cppformat without having un-casted support for
other pointers.

This is the change I did to my local copy of cppformat to make "%s", "cstring" work as
wanted/expected:

    diff --git a/platform/cppformat/format.cpp b/platform/cppformat/format.cpp
    index 129e6f0..8fa7b96 100644
    --- a/platform/cppformat/format.cpp
    +++ b/platform/cppformat/format.cpp
    @@ -463,13 +463,19 @@ class BasicArgFormatter : public ArgVisitor<Impl, void> {
       }
     
       void visit_string(Arg::StringValue<char> value) {
    -    writer_.write_str(value, spec_);
    +    if (spec_.type_ && spec_.type_ == 'p')
    +      visit_pointer(value.value);
    +    else
    +      writer_.write_str(value, spec_);
       }
     
       using ArgVisitor<Impl, void>::visit_wstring;
     
       void visit_wstring(Arg::StringValue<Char> value) {
    -    writer_.write_str(value, spec_);
    +    if (spec_.type_ && spec_.type_ == 'p')
    +      visit_pointer(value.value);
    +    else
    +      writer_.write_str(value, spec_);
       }
     
       void visit_pointer(const void *value) {

**Comment by vitaut** [comment]
Good catch, thanks! You are quite right that `printf("%p", "cstring")` should work but the fix needs a bit more work to prevent formatting of objects of type `std::string` as pointers. I'll look into it shortly.

**Comment by vitaut** [comment]
Fixed in https://github.com/cppformat/cppformat/commit/8b86a74ad5988be4dcefecfc794e2b79f94624ab. Now the following is supported:

```c++
  fmt::print("{:p}", "test");
  fmt::printf("%p", "test");
```
Thanks for reporting.
