### ISSUE TITLE
formatting bool with 's' type specifier should give textual output

### ISSUE THREAD

**Issue by LarsGullik** [cppformat/cppformat#224]
It is nice that the default for ("{}", true) -> "true", but it would be nice if "{:s}" and "%s"
did that as well.

I have a patch for this, but I am very unsure if it is done as it should be.
Note that my local copy has added FMT_ to the type enumerators (Had collisions with
pre-existing typedefs.)

    diff --git a/platform/cppformat/api/cppformat/format.hpp b/platform/cppformat/api/cppformat/format.hpp
    index 6e8fc57..e9a2ef0 100644
    --- a/platform/cppformat/api/cppformat/format.hpp
    +++ b/platform/cppformat/api/cppformat/format.hpp
    @@ -860,6 +860,7 @@ struct Value {
       };
     
       union {
    +    bool bool_value;
         int int_value;
         unsigned uint_value;
         LongLong long_long_value;
    @@ -1009,7 +1010,7 @@ class MakeValue : public Arg {
     #define FMT_MAKE_VALUE(Type, field, TYPE) \
       FMT_MAKE_VALUE_(Type, field, TYPE, value)
     
    -  FMT_MAKE_VALUE(bool, int_value, FMT_BOOL)
    +  FMT_MAKE_VALUE(bool, bool_value, FMT_BOOL)
       FMT_MAKE_VALUE(short, int_value, FMT_INT)
       FMT_MAKE_VALUE(unsigned short, uint_value, FMT_UINT)
       FMT_MAKE_VALUE(int, int_value, FMT_INT)
    @@ -1211,7 +1212,7 @@ class ArgVisitor {
         case Arg::FMT_ULONG_LONG:
           return FMT_DISPATCH(visit_ulong_long(arg.ulong_long_value));
         case Arg::FMT_BOOL:
    -      return FMT_DISPATCH(visit_bool(arg.int_value != 0));
    +      return FMT_DISPATCH(visit_bool(arg.bool_value));
         case Arg::FMT_CHAR:
           return FMT_DISPATCH(visit_char(arg.int_value));
         case Arg::FMT_DOUBLE:
    diff --git a/platform/cppformat/format.cpp b/platform/cppformat/format.cpp
    index 8fa7b96..20717c7 100644
    --- a/platform/cppformat/format.cpp
    +++ b/platform/cppformat/format.cpp
    @@ -379,6 +379,15 @@ class ArgConverter : public fmt::internal::ArgVisitor<ArgConverter<T>, void> {
           }
         }
       }
    +
    +  void visit_bool(bool value) {
    +    if (type_ == 's') {
    +      arg_.type = Arg::FMT_BOOL;
    +      arg_.bool_value = value;
    +    } else {
    +      visit_any_int(value);
    +    }
    +  }
     };
     
     // Converts an integer argument to char for printf.
    @@ -424,7 +433,7 @@ class BasicArgFormatter : public ArgVisitor<Impl, void> {
       void visit_any_double(T value) { writer_.write_double(value, spec_); }
     
       void visit_bool(bool value) {
    -    if (spec_.type_) {
    +    if (spec_.type_ && spec_.type_ != 's') {
           writer_.write_int(value, spec_);
           return;
         }

**Comment by vitaut** [comment]
Thanks for the suggestion, but `str.format` is following Python's convention:

```
>>> '{:s}'.format(True)
...
ValueError: Unknown format code 's' for object of type 'bool'
```

I'd rather keep this behavior especially since you can already get textual formatting by default:

```c++
 fmt::format("{}", true); // gives "true"
```

`printf` is a different matter because you can't omit a format specifier there. However making `%s` support bool will break compatibility with standard `printf`.

**Comment by LarsGullik** [comment]
Fair enough.

Would have been really nice to have way to print textual booleans with printf format though.

**Comment by vitaut** [comment]
If we add support for textual formatting of `bool` with `%s`, then

```c++
fmt::printf("%s", true);
```
will print "true", while 
```c++
std::printf("%s", true);
```
will be an error (most likely segfault). This may not be a big problem considering that GCC warns about it and `std::printf` is unsafe anyway.

**Comment by vitaut** [comment]
Fixed in https://github.com/cppformat/cppformat/commit/2157375d5ca892b83cd8602344b9cd6095bb9486. Thanks for the suggestion.
