### ISSUE TITLE
UtilTest.StringRefCompare: fails if std::char_traits<T>::compare returns a value outside [-1;1]

### ISSUE THREAD

**Issue by jackyf** [cppformat/cppformat#225]
Hi,

Thank you for the portability patch merges. Still one new issue on a newest master:

Extract from running tests on Debian s390x and arm64 autobuilders:
-------------------8<--------------------
[ RUN      ] UtilTest.StringRefCompare
/«BUILDDIR»/cppformat-2.0.0~alpha~20151107+ds3/test/util-test.cc:726: Failure
Value of: StringRef("fop").compare(StringRef("foo"))
  Actual: 8
Expected: 1
/«BUILDDIR»/cppformat-2.0.0~alpha~20151107+ds3/test/util-test.cc:727: Failure
Value of: StringRef("foo").compare(StringRef("fop"))
  Actual: -8
Expected: -1
[  FAILED  ] UtilTest.StringRefCompare (0 ms)
------------------->8---------------------

**Comment by vitaut** [comment]
Fixed in https://github.com/cppformat/cppformat/commit/aa741bafe6cf3c521f44b88e1d63af832b115b3e. Thanks!
