### ISSUE TITLE
using with Borland RAD Studio

### ISSUE THREAD

**Issue by rjdgtn** [cppformat/cppformat#227]
I try to use it Borland RAD Studio, but has compilation errors. 
Is this lib Borland compatible?

**Comment by vitaut** [comment]
I haven't tested compatibility with Borland C++ compiler (if that's what is used in RAD Studio), but would be happy to fix any compatibility issues. What errors do you get?

**Comment by vitaut** [comment]
Fixed in https://github.com/cppformat/cppformat/commit/ee3e68dc166b840276cdca0231de72cc8d5e6808.

**Comment by rjdgtn** [comment]
thanks. I will try again as soon as possible.
