### ISSUE TITLE
format.h: use of _ecvt(x, 0, &dec, &sign) causes compilation error in VS2013

### ISSUE THREAD

**Issue by gabime** [cppformat/cppformat#233]
error C4996: '_ecvt': This function or variable may be unsafe. Consider using _ecvt_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS.

**Comment by vitaut** [comment]
Fixed in https://github.com/cppformat/cppformat/commit/0519737b95532efb9a110e6543ca0fc930cbfb05. Thanks!
