### ISSUE TITLE
VS2013 performance  warning for _isnan

### ISSUE THREAD

**Issue by gabime** [cppformat/cppformat#234]
format.h(283): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)

**Comment by vitaut** [comment]
Fixed in https://github.com/cppformat/cppformat/commit/f60c4b994765f20a60b3038d9c52823eeb07c297 and more in https://github.com/cppformat/cppformat/commit/222f2d28f58b315ae7dfdbcdaf47889f97132cc9.
