### ISSUE TITLE
Optional additional format error handling method

### ISSUE THREAD

**Issue by Jopie64** [cppformat/cppformat#238]
# Details
I propose to add an additional method for handling format errors like this:
Instead of throwing or asserting, set a custom callback function for handling the format error. Also add an optional precompiler definition, e.g. FMT_TRACK_FILE_LINE. When enabled BasicWriter<>::write() function will keep track of where it is called, and on a format error, it will pass this info to the custom error callback function.

I was wondering, when I implement this, is there a possibility it will be accepted in the main code base? I will try to keep it as clean as possible of course.
Any other ideas of how to implement a feature like this more cleanly?

# Why this feature?
Because errors like this are not checked at compile time, sometimes they slip through the tests and are shipped to the customer. It is very convenient to see in a customer logfile where in the code this format error is generated. With this feature, this can be accomplished.
For the company I work for, we did something like this in a previous version of cppformat. But because it is not in the main code base, this feature is not maintained. And we have to re-implement it sometimes for newer versions of cppformat which is not that simple.

**Comment by vitaut** [comment]
Thanks for the proposal, this might be quite useful. I'll be happy to accept it in the main repo provided that it can be implemented in a reasonable manner without interfering too much with existing functionality (and it probably can). One question though: how can `BasicWriter<>::write()` keep track of where it is called? I thought that it is only possible in macros via `__FILE__`, `__LINE__`.

**Comment by Jopie64** [comment]
Thanks for your interest. I'm experimenting with it already and it poses a question. See [this commit](https://github.com/Jopie64/cppformat/commit/da0df501e5b7fc1beec2b860ed955891d2d97861).
This would work when `FMT_HEADER_ONLY` is not defined. But when it is, the complete .cc file is included into the header file. And when the header is used in multiple compilation units, the compiler complains about multiple definitions of the same function. I have tried to make those functions static or inline, which causes other problems when _not_ using `FMT_HEADER_ONLY`. I think I can probably work around this by making those functions static member functions of some class, which might be a little dirty. But then I came to wonder, how would you fix those kind of issues? You must have had them too before right?

**Comment by Jopie64** [comment]
I made it compilable in all cases by making the concerning function inline when `FMT_HEADER_ONLY` is defined. Still not sure whether this is OK though. What do you think? Its now like [this](https://github.com/Jopie64/cppformat/commit/833b6ba988b9a2c1b3864de6fe83374d08d34ace).

And to answer your question:
Yes, it is only possible using macros. I've to think about how to do this relatively cleanly. One way would be to add an extra function like `BasicWriter<>::writefl()` which would accept a file and line parameter.
And then a macro could be added in the form of:
```c++
#define FMT_WRITE(...) writefl(__FILE__,__LINE__, __VA_ARGS__)
```

The user could could then be something like
```c++
#define writefl FMT_WRITE
string f() {
  return fmt::MemoryWriter().writefl("{}", "hello").c_str();
}
```
I've to experiment a bit with it to find a nice way.

**Comment by vitaut** [comment]
I think this can be implemented in a non-intrusive way with a wrapper function that catches `FormatError` and adds location info to it:
```c++
#include "format.h"

struct ErrorWithLoc : fmt::FormatError {
  std::string filename;
  int lineno;
  
  ErrorWithLoc(const fmt::FormatError &e, const char *filename, int lineno)
  : fmt::FormatError(e), filename(filename), lineno(lineno) {}
};

void do_printfl(const char *filename, int lineno,
                const char *format_str, fmt::ArgList args) {
  try {
    fmt::print(format_str, args);
  } catch (const fmt::FormatError &e) {
    throw ErrorWithLoc(e, filename, lineno);
  }
}
template <typename... Args>
void do_printfl(const char *filename, int lineno,
                const char *format_str, const Args & ... args) {
  typename fmt::internal::ArgArray<sizeof...(Args)>::Type array;
  do_printfl(filename, lineno, format_str,
    fmt::internal::make_arg_list< fmt::BasicFormatter<char> >(array, args...));
}

#define printfl(...) do_printfl(__FILE__, __LINE__, __VA_ARGS__)

int main() {
  try {
    printfl("{:s}", 42);
  } catch (const ErrorWithLoc &e) {
    fmt::print("{}:{}: {}\n", e.filename, e.lineno, e.what());
  }
}
```
This prints 
```
test.cc:31: unknown format code 's' for integer
```
Example above rethrows exception, but you can use a callback if you like.

This doesn't require any changes to the format library except for maybe moving `ArgArray` to the public API.

**Comment by vitaut** [comment]
@Jopie64 Will the method proposed above work for you?

**Comment by Jopie64** [comment]
I haven't had the time to work on it the last days :) I'll look into it the coming week.
Your proposal is about the way I did it before with a previous version. But it might be sufficient because I suspect the api will not change so much anymore like it did in the past. :)
One thing though, one error is detected in the header file. And there assert () is always called regardless of the

**Comment by Jopie64** [comment]
Oops, pressed the wrong button. I'm using my phone :)
Anyway as I was saying, Throw() is not called from the header because it is not available there probably because of the FMT_HEADERONLY flag. That problem was fixed in my commit above, although it also introduced a custom error handler.
Anyway, I'll look into it next week. Thanks for your suggestions.

**Comment by vitaut** [comment]
> But it might be sufficient because I suspect the api will not change so much anymore like it did in the past.

I don't expect the documented public API change much after version 2.0. The main breaking change in 2.0 was a switch to `CStringRef`, but otherwise it's mostly source compatible with 1.1. The `ArgList`-related stuff will have to change because it currently relies on some internal API.

> Anyway as I was saying, Throw() is not called from the header because it is not available there probably because of the FMT_HEADERONLY flag. That problem was fixed in my commit above, although it also introduced a custom error handler.

If you mean this assert

```c++
      FMT_ASSERT(false, "invalid argument type");
```
then it is not reported as an exception because it shouldn't be triggered by a valid code that uses public API. The only way to trigger it is to somehow set an invalid type in an `Arg` object (unless there is a bug in the C++ Format library in which case it should be fixed rather than handled as an exception).

**Comment by Jopie64** [comment]
I'll close this issue for now because I'm not able to acquire time for it...
