### ISSUE TITLE
Visual Studio 12 /W4 warnings

### ISSUE THREAD

**Issue by Naios** [cppformat/cppformat#244]
**Revision 5c76d107cbaf5e8**

## warning C4510
TrinityCore\dep\cppformat\format.h(981): warning C4510: 'fmt::internal::DummyStream' : default constructor could not be generated ([TrinityCore\src\common\Collision\Models\GameObjectModel.cpp](https://github.com/TrinityCore/TrinityCore/blob/6.x/src/common/Collision/Models/GameObjectModel.cpp))

## warning C4610
TrinityCore\dep\cppformat\format.h(981): warning C4610: struct 'fmt::internal::DummyStream' can never be instantiated - user defined constructor required ([TrinityCore\src\common\Collision\Maps\MapTree.cpp](https://github.com/TrinityCore/TrinityCore/blob/6.x/src/common/Collision/Maps/MapTree.cpp))

**Comment by vitaut** [comment]
Fixed in https://github.com/cppformat/cppformat/commit/7836349ccc94512f93825b6a41264d065ca59b26. Thanks for reporting.

**Comment by vitaut** [comment]
Bummer, accidentally pushed some unintended changes. Anyway, this should be fixed in master now.
