### ISSUE TITLE
Bad use of #pragma clang diagnostic pop results in unbalanced push/pop operations

### ISSUE THREAD

**Issue by nicola-gigante** [cppformat/cppformat#246]
At the end of ```format.h``` we find the following code:

```
#ifdef __clang__
# pragma clang diagnostic pop
#endif
```

However, there seems to be no ```#pragma clang diagnostic push``` anywhere in the code. 
This results in a mismatch of push/pop operations when the header itself is included after a push, for example:

```
#pragma clang diagnostic push
#include "format.h"
#pragma clang diagnostic pop
```

The above results into a warning ("pop cannot pop, no matching push pragma"). I'm not sure why this warning does not come up when the header is included by itself, since there should be a mismatched pop operation anyway. But since the header also use ```#pragma GCC diagnostic push```, maybe this is interacting in some way.

So something should be done to fix the use of diagnostic push/pop I think..

**Comment by nicola-gigante** [comment]
I just noticed that using ```#pragma GCC diagnostic push``` makes no difference. I think the problem stems from the fact that clang interprets both ```GCC``` and ```clang``` pragmas, while g++ only interprets those tagged with ```GCC```. This asymmetry is indeed difficult to handle...

**Comment by vitaut** [comment]
There is `#pragma clang diagnostic push` in  https://github.com/cppformat/cppformat/blob/1cba0aea27915c06192b47f2d4429c8ddaad3aa8/format.h#L118 and I don't get any warning when compiling:

```c++
#pragma clang diagnostic push
#include "format.h"
#pragma clang diagnostic pop
```

What version of the library do you use?

**Comment by nicola-gigante** [comment]
An old one, indeed. 
The HEAD does not reproduce the problem. Sorry for the noise.

**Comment by vitaut** [comment]
No worries. Glad it had been fixed already =).
