### ISSUE TITLE
operator bool

### ISSUE THREAD

**Issue by bumbar1** [cppformat/cppformat#247]
Not sure if it's a bug (maybe it's expected behavior because of `bool`?), but if you define a custom data type with `operator bool` (regardless of return value) and `operator <<`, then formatting doesn't work.

Example code:
```
#include <iostream>
#include <string>
#include "cppformat/format.h"

struct Date {
    operator bool() const { return true; }
    friend
    std::ostream& operator << (std::ostream& os, const Date& date) { return os << "1.1.1970"; }
};

int main() {
    std::cout << "date is " << Date{} << "\n";
    std::cout << fmt::format("date is {}\n", Date{}); // prints "date is 1"
}
```

**Comment by vitaut** [comment]
I think this has been fixed already in https://github.com/cppformat/cppformat/commit/6cff6d81374fef37bedc3f82eefb9a01ee48e60b. The commit message mentions enums but the same applies for any type implicitly convertible to int. Using the current master branch I get:

```
date is 1.1.1970
date is 1.1.1970
```

**Comment by bumbar1** [comment]
Ah yes, apologies. I wasn't using the latest version. It's working with `operator bool` defined. Thanks.

**Comment by vitaut** [comment]
No problems. Thanks for the confirmation.
