### ISSUE TITLE
No support for MSVC 2008?

### ISSUE THREAD

**Issue by ibell** [cppformat/cppformat#253]
I didn't see MSVC2008 listed as a potential compiler.  As you probably know, on windows, with python 2.7, we typically need to compile with MSVC2008.  I'd like to use your library in a python2.7 extension, but no MSVC2008 = no cppformat.  Have I misunderstood?

**Comment by vitaut** [comment]
#236 seems to include a fix that allows compilation on MSVC2008, but I'm not using Windows or MSVC myself, so I can't confirm it.

**Comment by vitaut** [comment]
I'm closing this for now, but if you get any errors on this compiler feel free to reopen and post the error messages.
