### ISSUE TITLE
Support for constraint environment

### ISSUE THREAD

**Issue by elazarl** [cppformat/cppformat#254]
Hi,

cppformat is a breath of fresh air, especially when you use it for embedded device where stupid errors could be costly.

Do you plan to make a subset of cppformat available for more constraint environment?

Specifically:

  1. Ability to turn off POSIX error handling. I don't have stderr, I only have serial.
  2. Ability to turn off classes that requires dynamic memory allocation - stack based alternative for MemoryWriter, and ability to turn off support for basic_string.
  3. Ability to turn off wchar support, which is not always available, and not always cost-effective to implement.
  4. Ability to use custom printing function, without requiring user to take all the c++ streams abstraction.

Would you accept pull requests in this direction?

**Comment by vitaut** [comment]
Hi,

Thank you for the nice feedback.

> Do you plan to make a subset of cppformat available for more constraint environment?

No, I don't have any plans specifically targeting constrained environments.

> [1] Ability to turn off POSIX error handling. I don't have stderr, I only have serial.

I'm not sure what you mean by that. The errors are reported as exceptions, but you can provide your own error handling mechanism via `FMT_THROW`.

> [2] Ability to turn off classes that requires dynamic memory allocation - stack based alternative for MemoryWriter, and ability to turn off support for basic_string.

I think turning off classes with dynamic memory allocation completely via conditional compilation will be too messy, but writing to a fixed, possibly stack-allocated, array is already supported:

```c++
char buffer[100];
fmt::ArrayWriter w(buffer);
w.write("The answer is {}", 42);
```
This could be wrapped in a function for even easier use:

```c++
char buffer[100];
format_array(buffer, "The answer is {}", 42);
```

> [3] Ability to turn off wchar support, which is not always available, and not always cost-effective to implement.

Again, I think it would be too messy to turn off completely, but it doesn't add any overhead if you don't use it.

> [4] Ability to use custom printing function, without requiring user to take all the c++ streams abstraction.

IOStreams are already optional and only used when formatting types that provide an overloaded ostream `operator<<`. You can provide a custom formatting function by overloading `format` instead:

```c++
void format(Formatter &f, const char *&format_str, const MyType &value) {
  // parse format_str and format value
}
```

I'm also open to pull requests that improve support for such environments provided that they don't obscure the code by introducing a lot of conditional compilation or similar. If you have any specific ideas, I recommend discussing them here or in separate issues before preparing a full PR (although a small prototype to demonstrate the idea might be useful).

**Comment by vitaut** [comment]
I'm closing this for now, but feel free to reopen or open another issue to discuss any specific suggestion in more details.
