### ISSUE TITLE
sprintf api integer enhancement

### ISSUE THREAD

**Issue by rglarix** [cppformat/cppformat#255]
Hi, the sprintf api is unnecessarily converting integer arguments, leading to inexact values.
As an example, the format string "%d" converts its argument to plain int, even if it was long or long long.
While the original sprintf had no type information and must do that, cppformat is smarter and could do much better, for example preserving original type information.
So one could simply write "%d" or "%u" and have cppformat format the string according to the real argument size.
This would be very useful esp. on windows, where some types change size going from 32 to 64bit, but others not, leading to bugs difficult to find.
Obviously you also can use the format api, but then you need to rewrite existing code, while the sprintf api brings immediate benefits just by adding cppformat.

**Comment by vitaut** [comment]
Thanks for the suggestion. I don't think it will benefit existing code, because it should already be using correct specifiers and switching to cppformat will have no effect other than introducing type safety. However, this may benefit the new code using cppformat's `printf`.

**Comment by vitaut** [comment]
This is implemented in https://github.com/cppformat/cppformat/commit/8474a6232d3b23fcf240329b579dd6f8284de54f. For example, the code

```c++
fmt::printf("%d", std::numeric_limits<long long>::max());
```
prints `9223372036854775807` now (provided that `long long` is 64-bit) while previously it printed `-1`.

Note that only narrowing conversions are disabled, sign and widening conversions still apply.

**Comment by rglarix** [comment]
Wonderful! I've been toying with a tentative implementation but yours is much more elegant.
I'll try it ASAP.
Thank you very much
