### ISSUE TITLE
MSVC2015 - warning 6326 - Potential comparison of a constant with another constant.

### ISSUE THREAD

**Issue by omascia** [cppformat/cppformat#263]
I think the linked picture says it all. I have a 6326 reported on line 1788 of format.h (2.0). On that line I see bool fm:internal::check<bool>(bool value) whose intent is to suppress bogus "conditional expression is constant". But it looks like "potential comparison of a constant with another constant" is emitted instead.
The attached partial print-screen shows the warning reported and the format.h line 1788 in context.
![w6326](https://cloud.githubusercontent.com/assets/16653543/12242881/da652ea6-b89b-11e5-90ec-86c2d2c4d6d6.png)

**Comment by vitaut** [comment]
Thanks for reporting this. The `make_arg_list` function has been dropped from the current development version (`master` branch) so you should no longer get this warning.

**Comment by omascia** [comment]
It is my understanding that I can for now safely ignore this warning. Am I right? (I'll test the master branch separately, but I'd like to release some code based on the 'released' code in between). Safe according to you?

**Comment by vitaut** [comment]
This is a completely useless (but annoying) warning, you can safely ignore it or suppress with a pragma.

**Comment by vitaut** [comment]
Since there is no `make_arg_list` any more I'm going to close this, but feel free to reopen (or open another issue) if you get a similar warning elsewhere.
