### ISSUE TITLE
Accessing MemoryWriter Without Converting

### ISSUE THREAD

**Issue by primesoftware** [cppformat/cppformat#272]
Is it possible to access the MemoryWriter stream directly? I would like to search it for a string pattern (sub string) and prefer not to covert to char or std::string first.

**Comment by mwinterb** [comment]
The [size() and data()](https://cppformat.github.io/latest/api.html#_CPPv2N3fmt11BasicWriter4sizeEv) functions do no transformations or memory allocations, so can be used for that purpose. Just be careful to not use it with functions that expect '\0' termination.

**Comment by vitaut** [comment]
Just to add to what @mwinterb wrote, `c_str` also provides access to the `MemoryWriter`'s buffer but adds a terminating null which can cause buffer reallocation.
