### ISSUE TITLE
Warning: 'control reaches end of non-void function' on OS X

### ISSUE THREAD

**Issue by dean0x7d** [cppformat/cppformat#274]
It's a minor issue:
```
cppformat/test/posix-mock-test.cc:516:1: 
warning: control reaches end of non-void function [-Wreturn-type]
```

Seems to originate here: [test/posix-mock-test.cc#L508](https://github.com/cppformat/cppformat/blob/master/test/posix-mock-test.cc#L508).

**Comment by vitaut** [comment]
Fixed in https://github.com/cppformat/cppformat/commit/6500f161f7302fb7253d4def7f4e1309c4f9a7f2. Thanks!
