### ISSUE TITLE
Feature Request: Simple if support

### ISSUE THREAD

**Issue by ddevienne** [cppformat/cppformat#275]
I'm starting to use CppFormat for longish dynamically generated Oracle PL/SQL code, consisting mostly of a long format with some named params, but within that long template, there are parts which are "optional" depending on context.

Dealing with these _optional parts_ requires either breaking the format into _before/after_ pieces, around each conditional part, or using placeholders for the conditional parts, and formatting those before-hand using separate fmt::format() calls. Neither solutions are great, and they both _**fragment**_ the format in pieces, hurting readability.

So, could CppFormat support a simple form of if-conditional, similar to more full-fledged templating engines, predicated on a bool arg? (using whatever syntax).

I know it's a bit of a stretch, but I guess it's worth asking, no? :) --DD

**Comment by vitaut** [comment]
Thanks for the suggestion, but I think conditionals are out of scope of this library. It is possible to build a templating engine on top of it, but I don't think this functionality belongs to the library itself. You can do formatting incrementally using a writer, for example:

```c++
  fmt::MemoryWriter w;
  w.write("Hello, {}! ", "World");
  if (print_answer)
    w.write("The answer is {}.", 42);
```
This will also fragment the format string though.

**Comment by ddevienne** [comment]
Indeed it will, which was what I hoped to avoid. But I understand your answer of course.

Note that this new feature could have been similar to the way justification can be conditioned on a runtime arg which is not itself "printed", but used to change the formatting of another arg. But that I mean there's a precedent to an arg affecting the output, but not being printed itself. The difference is that its effect is more limited to a single placeholder, doesn't go into nesting of conditions, etc...

**Comment by vitaut** [comment]
> Note that this new feature could have been similar to the way justification can be conditioned on a runtime arg which is not itself "printed", but used to change the formatting of another arg.

Right, but this only affects formatting of a single argument. Going beyond this would considerably increase complexity of the library. But as I wrote before, it's possible to build a templating engine on top of existing functionality. One possible way is to extend `BasicFormatter` with a new formatting class, doing parsing of conditionals there and reusing the individual argument formatting machinery.
