### ISSUE TITLE
Suggestion: Just return `format_str` from `fmt::format` when used without additional arguments.

### ISSUE THREAD

**Issue by FrankStain** [cppformat/cppformat#278]
Hi there!

It would be much useful if `fmt::format` will just return `format_str`, without parsing, when no additional arguments passed to function.
There are some situations present in my business, when i want to use `fmt::format` and know that sometimes it will format nothing. I'm actually not satisfied with decision to overload or wrap `fmt::format` by myself.

So... mby it would be good idea to introduce one small overload of `fmt::format` that will take only one argument and will just return this argument?

**Comment by vitaut** [comment]
Hi, @FrankStain.

Thanks for the suggestion, this is a valid use case and I thought about it before. However, the whole purpose of `fmt::format` is to do formatting, so adding an overload that doesn't would be a bit counter-intuitive. It would also differ from the behavior of both Python's `str.format`, this function is modeled after, and `std::printf`.

Also there is no need to call `fmt::format` at all if you don't have any arguments. You can use the source string directly. But if you have an example where it is not possible/desirable, I would be interested in seeing it.

**Comment by FrankStain** [comment]
Hey, @vitaut :)

So, for ex. here is my abstract examples of practical problems...

First, i may need to use formated logs, collaborating it with debug information.
```.cpp
#define MY_LOG( MSG, ... ) MY_DEBUG_LOG( __FILE__, __LINE__, fmt::format( MSG, ##__VA_ARGS__ ) )
```
For now, i just write before this macro next overload.
```.cpp
namespace fmt
{
	inline std::string format( const std::string& format_str )
	{
		return format_str;
	};
};
```
So now in case of `MY_LOG( "hello world." )` i have no overrun on parsing.

Next example. Call of `fmt::format` may be proxied from other templated function with parameter pack. And, yep, such function may be called with empty parameter pack.
```.cpp
template< typename ... TArguments >
void DoStuff( TArguments ... arguments )
{
	// Some stuff...
	if( /* smth going wrong... */ )
	{
		// `s_msg_format` is valid format string, that received from outside.
		PushMessageSomewhere( fmt::format( s_msg_format, arguments ) );
	};
};
```
In this situation i need to do one of two things. First is described above. Second one is an static specialization of `DoStuff` where it receives no arguments.

Second case is more often.
In all such situations i tries to escape from that small overrun on string parsing inside `fmt::format`.
I know, it may sounds silly or funny, but i always prefer spending processor time only for valuable operations.

**Comment by vitaut** [comment]
Thanks for the example. Just to clarify, by "overrun" do you mean computational overhead incurred by formatting? If performance is a concern, you can avoid both `fmt::format` call and `std::string` construction/copying completely by doing something like:

```c++
if (sizeof...(TArguments) > 0)
  PushMessageSomewhere(s_msg_format); // std::string construction/copying can be avoided
else
  PushMessageSomewhere( fmt::format( s_msg_format, arguments ) );
```
provided that `PushMessageSomewhere` can benefit from this which is easy to do using `string_view`.

Note that `std::string` allocation takes significant fraction of `fmt::format`'s time at least if the resulting string is not too big.

Another thing to consider is that
```c++
    std::string format( const std::string& format_str )
    {
        return format_str;
    }
```

is not equivalent to the no-argument version of variadic `fmt::format` because the latter processes argument placeholders `{...}`. In particular, if the user forgets to pass an argument:

```
fmt::format("The answer is {}.");
```
this will throw an exception while the version of format that simply returns its argument won't.

For these reasons, I think it's better to keep the existing behavior.

**Comment by FrankStain** [comment]
> Just to clarify, by "overrun" do you mean computational overhead incurred by formatting?

Not formatting as it is (i mean formatting of actual arguments), but only parsing of `format_str` and looking for patterns in cases where no argument was passed to be formated.

This code, in my thoughts, causes overrun when only `format_str` passed to `fmt::format`:
https://github.com/cppformat/cppformat/blob/master/cppformat/format.h#L3675
And yep, i don't need any exception if i have any unresolved "{}" token inside, i just don't care about it cuz `format_str` will not contain it for such cases.

I see your arguments. My suggestion is not universal and covers only small part of possible function usages. At this moment i become satisfied with my own small overload of `fmt::format`.
Thanks for discussion! :)

**Comment by vitaut** [comment]
Cool. Thanks for using the library =).
