### ISSUE TITLE
CppFormat causing exceptions

### ISSUE THREAD

**Issue by VikingExplorer** [cppformat/cppformat#279]
I really need some help.  I've determined that this line is causing exceptions in another part of our codebase:

return fmt::format( fmt.value(), std::forward<Args>( args )... );

I've got a try/catch around this, but it's not catching anything.  fmt.value() is a wstring.  

Additional Info:  my framework is targeting Win-Desktop, Android, iOS, WinU, etc.  It's the WinD version that is throwing a strange exception.  All of the client code calling this method is still set up with normal printf codes, like %s, %d, etc.  However, it would be disturbing if malformed format strings cause instabilities.

**Comment by vitaut** [comment]
I don't see anything wrong with the code that you posted. What exception do you get and if it is not thrown from `fmt::format` what exactly is the problem with the latter?

**Comment by VikingExplorer** [comment]
Thanks for responding. 
Exception thrown at 0x0FAA3FF0 (ucrtbased.dll) in Enterprise Std Employee Edition.exe: 0xC0000005: Access violation reading location 0xD525F2F6.

1) The call stack is indicating a place not even close to where the CppFormat call is.
2) I have confirmed with about 10 complete rebuilds that with this one CppFormat line commented out, it works fine. With it in, the same exception happens, at the exact same spot.  Completely reproducible.

The whole function. This exception catches nothing.
			static String message( const String& fmt, Args&&... args )
			{
				try
				{
					return fmt::format( fmt.value(), std::forward<Args>( args )... );
				}
				catch( const exception& e ) 
				{
					//fmt::printf( "%s\n", e.what() );
					TRACE( "CppFormat: %s\n", e.what() );
				}
				return String::empty();
			}

![cppformat](https://cloud.githubusercontent.com/assets/15109208/13326314/55d105da-dbb3-11e5-8b1c-a9fbf00604cf.PNG)

**Comment by dean0x7d** [comment]
Just a shot in the dark: if the `std::forward` is being used incorrectly, you could have a use-after-move problem at a later point in the code (trying to use an arg which has been moved out).

**Comment by VikingExplorer** [comment]
yea, variadic templates & argument forwarding is new to me. What should I do to prevent that?

**Comment by vitaut** [comment]
First you can get rid of `std::forward` and pass arguments by const ref. I don't think there is any benefit in forwarding arguments because `fmt::format` takes everything by const ref itself.

Also it might be a good idea to use something like valgrind (not sure what's Windows equivalent) to catch memory errors.

**Comment by VikingExplorer** [comment]
What would be the syntax without std::forward?

**Comment by vitaut** [comment]
Something like

```c++
template < typename... Args >
String message( const String& fmt, const Args&... args )
{
return fmt::format( fmt.value(), args... );
}
```

Also what is `String`? If it is some custom string implementation, how does its ctor from `std::string` look like?

**Comment by dean0x7d** [comment]
I'm not sure what your actual code is. The snippet you posted seems to be missing the template parameters for the function. Also, `std::forward` must always be called with an explicit type which seems to be missing in the code you posted. In general, this is the basic pattern for forwarding:

```c++
template<class... Args>
int outer(Args&&... args) {
	return inner(std::forward<Args>(args)...);
}
```

Deviating from that will have surprising results. For example, the following code will not do forwarding even if it looks similar:

```c++
template<class... Args>
class A {
	// never do this
	int outer(Args&&... args) {
		return inner(std::forward<Args>(args)...);
	}
}
```

That's because the arg types need to be deduced immediately for the `&&` to do its magic.

It's easy to get burned with forwarding and as @vitaut mentioned `fmt::format` take everything by const ref anyway, so you can just do:

```c++

template<class... Args>
String message(const String& fmt, const Args&... args) {
	return fmt::format(fmt.value(), args);
}
````

**Comment by VikingExplorer** [comment]
dean,  GitHub was swallowing that LOC, so I added spaces in a subsequent edit.

vitaut, my String class looks like:
	class String
	{
		private:
			wstring Value;

		public:
			String();
			String( const String& cs );
			String( String&& cs );
			
			String( const wchar_t* );
			String( const wstring& );
			String( wstring&& );
			
			String( const string& );
			String( string&& );

Full rebuild with this code:
			template< typename... Args >
			static String message( const String& fmt, const Args&... args )
			{
				try
				{
					//return fmt::format( fmt.value(), std::forward<Args>( args )... );
					return fmt::format( fmt.value(), args... );

But it stills has a crash, same as before.

**Comment by dean0x7d** [comment]
It doesn't look like anything is wrong with regard to `fmt::format`. Maybe have a look at what the `String` constructors are doing. I guess `String( wstring&& )` is the relevant one here and perhaps `String( const String& cs )` / `String( String&& cs )` depending on what optimizations the compiler is applying.

If the constructors are OK, I can't say I have any other idea. You'll need a valgrind-like tool to more closely pinpoint where the access violation is happening.

**Comment by VikingExplorer** [comment]
```
String::String( wstring&& wide )
	: Value( wide )
{}
String::String( const String& cs )
	: Value(cs.Value)
{}

String::String( String&& cs )
	: Value( move( cs.Value) )
{}
```
Btw, I tried replacing call to fmt::format with:
```
				TRACE( fmt.value().c_str(), args... );
```
And it ran just fine.   So, I'm throwing all sorts of format strings at this which are in a printf style with %ls and what not. I'm assuming that anything bad should cause an exception.

**Comment by Spartan322** [comment]
is `TRACE` a macro?

**Comment by VikingExplorer** [comment]
Yes, MFC macro, which is CTraceFileAndLineInfo behind the scenes..  I was just trying to isolate whether it was variadic templates or fmt::format.

**Comment by Spartan322** [comment]
macros evaluate all the way out in the preprocessor, so actions in macros can't really be compared to function unless it calls the function anyway.

**Comment by mwinterb** [comment]
Are you using VS2015 RTM? The ucrtbased.dll that was distributed with the base installation did not have PDBs released. Is it feasible to update to Update 1 and see if better a more useful callstack can be obtained.
Alternately, I _think_ that if you install the latest Windows 10 SDK, the ucrtbased may get updated. Going that route may also be a much quicker installation process, too.

**Comment by vitaut** [comment]
@VikingExplorer does replacing the call to `fmt::format` with the call to the following function

```c++
template <typename... Args>
String test(const String &fmt, const Args & ... args) {
  return fmt;
}
```

i.e. changing `message` to something like:

```c++
template< typename... Args >
static String message( const String& fmt, const Args&... args ) {
  try {
    return test( fmt.value(), args... ); // call `test` instead of `fmt::format`
  ...
```
make the issue go away?

**Comment by dean0x7d** [comment]
A little bit off-topic, because this probably isn't the issue, but this constructor is wrong:
```c++
String::String( wstring&& wide )
    : Value( wide )
{}
```
It's going to copy. It needs an extra `std::move` to actually invoke the move constructor for `Value`:
```
String::String( wstring&& wide )
    : Value( std::move(wide) )
{}
```

Also, since the `String( const String& cs )` / `String( String&& cs )` are just doing default copy and move constructor work, you can omit them completely or at least `= default` them.

**Comment by VikingExplorer** [comment]
I am using VS2015 Update 1.

I think I have the latest Win10 sdk. These VS installations are quite recent. This is what it says when I clicked on Install from winSDK site.

![win10sdk](https://cloud.githubusercontent.com/assets/15109208/13333829/f728df70-dbd6-11e5-8e1e-191b0b81bb6b.PNG)

Thanks Dean.

vitaut, doing a full rebuild to make sure, but it looks like your test reveals that fmt::format is off the hook. So, while that's building, any ideas on how to figure out what crazy arguments are causing this?

**Comment by VikingExplorer** [comment]
Does this look problematic?
```
void String::trace( String&& contextualFormat ) const
{
	Log::debug_msg( contextualFormat, *this );
```
Am I right or wrong in thinking that any user defined type can be passed using arg forwarding?

This time, the above lines of code are in the call stack. 

contextualFormat = {Value=L"RdbApplication::register_model -> %ls has already been registered\n" }
*this = 0x0019f1e0 {Value=L"WorkUnit" }

Any ideas about what on earth could be going on here?  Function looks like:
```
			template<typename... Args>
			static void debug_msg( const String& fmt, const Args&... args )
			{
				auto msg = test( fmt, args... ); // call `test` instead of `fmt::format`
#ifdef WIN_D
				TRACE( msg.value().c_str() );
#endif
			}
```
It does not crash if the TRACE line is removed, so it's happening because I try to use msg?

**Comment by VikingExplorer** [comment]
Do I need to go back to perfect forwarding with std::forward to avoid automatic demotions?

**Comment by vitaut** [comment]
I'm not sure what could be causing the problem. Anyway, since this doesn't look like a bug in `format`, I'm closing this.
