### ISSUE TITLE
Linker error when linking to library that uses cppformat

### ISSUE THREAD

**Issue by TheCodeInside** [cppformat/cppformat#284]
I'm attempting to incorporate cppformat into [an engine](https://github.com/TheCodeInside/HatchitCore/tree/dev) I'm helping with, but I'm getting a linker error on Windows (using Visual Studio 2015) whenever I try to build the test project. The engine itself compiles fine with cppformat and internally calling the function that uses `fmt::sprintf` is fine ([file for reference](https://github.com/TheCodeInside/HatchitCore/blob/dev/include/ht_debug.h)), but in the Google Test project I'm getting the following linker errors:

```
LNK2019	unresolved external symbol "__declspec(dllimport) public: void __cdecl fmt::internal::PrintfFormatter<char>::format(class fmt::BasicWriter<char> &,class fmt::BasicCStringRef<char>)"
LNK2001	unresolved external symbol "__declspec(dllimport) public: void __cdecl fmt::internal::PrintfFormatter<char>::format(class fmt::BasicWriter<char> &,class fmt::BasicCStringRef<char>)
```

However, when I compile the project under Linux (Ubuntu 14.04 with G++ 5.3) everything compiles fine and the tests run successfully.

I initially believed the problem was caused by a templated method being implemented in a file other than the header, but I don't think that that would explain why there are no problems on Linux.

**Comment by vitaut** [comment]
In what exactly project do you get linker errors, one of the C++ Format tests? Could you post the full build log?

**Comment by vitaut** [comment]
You need to define `FMT_EXPORT` to export symbols from a shared library (DLL). It is done automatically for the `cppformat` library, but since you build it as a part of your own library, you need to do it yourself.

**Comment by TheCodeInside** [comment]
[I already do that](https://github.com/TheCodeInside/HatchitCore/blob/dev/include/ht_platform.h#L46-L56), and Visual Studio shows that it is defined before `format.h` is included.

**Comment by vitaut** [comment]
Does `HatchitCore.dll` export `??$printf@D@fmt@@YAXAEAV?$BasicWriter@D@0@V?$BasicCStringRef@D@0@VArgList@0@@Z`? You can check it with Dependency Walker.

**Comment by TheCodeInside** [comment]
It seems like these are the only `cppformat` symbols that are being exported are `??4?$BasicData@X@internal@fmt@@QEAAAEAU012@$$QEAU012@@Z` and `??4?$BasicData@X@internal@fmt@@QEAAAEAU012@AEBU012@@Z`.

**Comment by vitaut** [comment]
Perhaps instantiations like

```c++
template void fmt::internal::PrintfFormatter<char>::format(
  BasicWriter<char> &writer, CStringRef format);
```
at the end of `format.cc` require `__declsped(dllexport)` too. Need to check that.

**Comment by TheCodeInside** [comment]
I just compiled `cppformat` by itself as a dynamic library and inspected it with Dependency Walker, and it's showing that `?format@?$PrintfFormatter@D@internal@fmt@@QEAAXAEAV?$BasicWriter@D@3@V?$BasicCStringRef@D@3@@Z` is indeed being exported. I wonder why it wouldn't be exported in Hatchit then?

**Comment by vitaut** [comment]
It's not enough to define `FMT_EXPORT` in `ht_platform.h` because the latter is not included in `format.cc`. You should define `FMT_EXPORT` on a project level instead, e.g.

```cmake
target_compile_definitions(<target> PRIVATE FMT_EXPORT)
```
as cppformat does.

**Comment by TheCodeInside** [comment]
Ahh, okay. That fixed it. Thank you!
