### ISSUE TITLE
Format with %x or %p?

### ISSUE THREAD

**Issue by paulsapps** [cppformat/cppformat#288]
Consider:

```
  int bar = 7;
  fmt::sprintf("yolo = %x", &bar);
  fmt::sprintf("yolo = %p", &bar);
  fmt::sprintf("yolo = {}", &bar);
```
This fails to compile in VS2013 update 5:

'fmt::internal::MakeValue<Formatter>::MakeValue' : cannot access private member declared in class 'fmt::internal::MakeValue<Formatter>'

test.cpp(2655) : see reference to function template instantiation 'std::string fmt::sprintf<int*>(fmt::CStringRef,int *const &)' being compiled

Is this expected to work? Or does one have to static_cast<void*>(&bar) for attempting to use %x/p?

**Comment by vitaut** [comment]
To format a pointer other than a pointer to a C string you should cast it to `void*`:

```c++
  fmt::sprintf("yolo = %p", static_cast<void*>(&bar));
  fmt::format("yolo = {}", static_cast<void*>(&bar));
```
