### ISSUE TITLE
Escaping "{" inside a JSON file

### ISSUE THREAD

**Issue by GP-GPU** [cppformat/cppformat#294]
Hi,
Is it possible to escape the "{" and the "}" characters inside a JSON file? 
e.g. {"x": "ddd", "y" : "{0}" }
cppformat throws an error because it can not determine the opening/closing parenthesis. 

Thanks,

**Comment by vitaut** [comment]
Yes, you can escape `{` and `}` by doubling, i.e. `{{` and `}}` as described in http://cppformat.github.io/latest/syntax.html.

**Comment by rcdailey** [comment]
Sorry to revive this from the dead but I wanted to offer my protest.

This isn't so easy to do, or practical to do, in certain situations. If I'm loading JSON data from an external source, such as an HTTP response, the curly braces will not be double-escaped. Would it be possible to allow the delimiters to be customized in the library? For example, allow us to use `%` instead or something? Or maybe build in an alternative, like `@1@` and `@fubar@`.

**Comment by vitaut** [comment]
> Would it be possible to allow the delimiters to be customized in the library? For example, allow us to use % instead or something?

@rcdailey, yes, you can use the printf API with `%` delimiter instead of the format API with `{}` delimiters.
