### ISSUE TITLE
vc++ 2015 update 2 cannot access private member declared in class 'fmt::internal::MakeValue<Formatter>'

### ISSUE THREAD

**Issue by pavel-pimenov** [cppformat/cppformat#300]
#define FMT_HEADER_ONLY
#include "../cppformat/format.h"

2>q:\vc15\r5xx\cppformat\format.h(1975): error C2248: 'fmt::internal::MakeValue<Formatter>::MakeValue': cannot access private member declared in class 'fmt::internal::MakeValue<Formatter>'

**Comment by vitaut** [comment]
This error is normally given when trying to format an argument which is explicitly forbidden, for example:

```c++
fmt::format("{}", L"test");
```
