### ISSUE TITLE
Documentation missing in .zip files

### ISSUE THREAD

**Issue by daveisfera** [cppformat/cppformat#301]
The .zip files for previous releases included the documentation, but the 2.0.1 and 2.1.0 releases do not include it. Ideally, the documentation could be built during packaging but this is not possible in Fedora because some of the tools are downloaded and some are expected to already be on the system. So, making it possible to build the documentation would be the optimal fix, but at least including it in the .zip files should be done in the short term.

**Comment by vitaut** [comment]
Thanks for the bug report. Currently there are some issues with building the documentation (#252) which I plan to address, hopefully, next week.

**Comment by daveisfera** [comment]
Sorry for the duplicate. I looked through the list of issues for something like this, but I guess I missed #252. You can either re-purpose this as a request to make building the documentation more friendly for packaging or just close it.

**Comment by vitaut** [comment]
Should be fixed in https://github.com/cppformat/cppformat/releases/tag/2.1.1.
