### ISSUE TITLE
Feature Request: Add "%.*s" format to fmt::format to output string with specified length, just like sprintf

### ISSUE THREAD

**Issue by alanqian** [cppformat/cppformat#303]
when we wanna output a string not terminate with asciiz, we can write as following:

char buffer[] = "foofoofoo";   // this is only a demo

int len = 6;  // can be other value

printf("%.*s", len, buffer);

will output "foofoo"

**Comment by vitaut** [comment]
This is already supported

```
  char buffer[] = "foofoofoo"; // this is only a demo
  int len = 6; // can be other value
  fmt::printf("%.*s", len, buffer);
```
prints `foofoo`.

**Comment by alanqian** [comment]
IMHO, fmt::printf version can only output to stdout, while I wanna to output to other stream like logger, I wanna another version like following:

logger->debug(fmt::format("{:.*s}\n", len, buffer));

---

// @file format_test.cc : test cppformat ".*s" format
//
// History:
//   Created by alan, 2016-04-11, <qian.guoxiang@qq.com>
//
// Tested on Mac OS X, 10.11.3 (15D21)
// cppformat revision: current master d8e246d

#include <iostream>
#include <cppformat/format.h>

int main(int argc, const char* argv[])
{
    char memory[] = "abcdefghijk"; // memory for testing
    int len = 8;  // output string length to test with

    // printf version, will output abcdefgh\n
    printf("%.*s\n", len, memory);

    // sprintf version, will output abcdefgh\n
    char tmp[64];
    sprintf(tmp, "%.*s\n", len, memory);
    std::cout << tmp;

    // fmt::printf version, that's ok
    fmt::printf("%.*s\n", len, memory);

    // The final python-like fmt::format version is the one I EXPECT,
    // but,
    // it will cause an exception `fmt::FormatError: missing precision specifier'
    std::cout << fmt::format("{:.*s}\n", len, memory);
    return 0;
}

**Comment by alanqian** [comment]
IMHO, fmt::printf can only output to stdout. When I wanna to output to stream like logger, I really want a python like format version like following:

```
logger->debug(fmt::format("{:.*s}", len, buffer));
```

here is a full test file.

---

```
// @file format_test.cc : test cppformat ".*s" format
//
// History:
//   Created by alan, 2016-04-11, <qian.guoxiang@qq.com>
//
// Tested on Mac OS X, 10.11.3 (15D21)
// cppformat revision: current master d8e246d

#include <iostream>
#include <cppformat/format.h>

int main(int argc, const char* argv[])
{
    char memory[] = "abcdefghijk"; // memory for testing
    int len = 8;  // output string length to test with

    // printf version, will output abcdefgh\n
    printf("%.*s\n", len, memory);

    // sprintf version, will output abcdefgh\n
    char tmp[64];
    sprintf(tmp, "%.*s\n", len, memory);
    std::cout << tmp;

    // fmt::printf version, that's ok
    fmt::printf("%.*s\n", len, memory);

    // The final python-like fmt::format version is the one I EXPECT,
    // but,
    // it will cause an exception `fmt::FormatError: missing precision specifier'
    std::cout << fmt::format("{:.*s}\n", len, memory);
    return 0;
}
```

**Comment by mwinterb** [comment]
There is a [sprintf](https://cppformat.github.io/latest/api.html#_CPPv2N3fmt7sprintfE10CStringRef7ArgList) analog that returns a std::string, but for integrating with the fmt::format, is there any reason to just pass a [fmt::StringRef](https://cppformat.github.io/latest/api.html#_CPPv2N3fmt14BasicStringRef14BasicStringRefEPK4CharNSt6size_tE)?

**Comment by alanqian** [comment]
### For coding style elegance:

To mixed with fmt::sprintf and fmt::format to a logger is not elegant, I'm forced to write this tedious version:

```
    logger->debug(fmt::format("handle write request ok, peer:{} memory:{}\n", 
                              peer->toString(),
                              fmt::sprintf("%.*s", len, memory)));
```

instead, I can write this elegant and simple version if fmt::format support it:

```
    logger->debug(fmt::format("handle write request ok, peer:{} memory:{:.*s}\n",
                              peer->toString(), len, memory));
```

### For fmt::format, lacks of variable precision format vs sprintf api;

    It's a feature, not just integration.

**Comment by vitaut** [comment]
The runtime length is supported by `fmt::format` too
```c++
fmt::format("{:.{}}", buffer, len);
```

Please see http://cppformat.github.io/2.0.0/syntax.html for more details.

**Comment by vitaut** [comment]
@alanqian BTW if you are interested in a logging library that uses C++ Format, have a look at [spdlog](https://github.com/gabime/spdlog).

**Comment by alanqian** [comment]
thank you, that's ok

**Comment by ZENOTME** [comment]
> The runtime length is supported by `fmt::format` too
> 
> ```c++
> fmt::format("{:.{}}", buffer, len);
> ```
> 
> Please see http://cppformat.github.io/2.0.0/syntax.html for more details.

I find one interesting thing. Use fmt::string_view has the same effect of this and higher performance. 
```
static void bench_fmt_var_len(benchmark::State& state) 
{
    for (auto _: state) {
        char buf[4] = {'1','2','3','4'};
        benchmark::DoNotOptimize(fmt::format("{:.{}}", buf, 4));
    }
}
BENCHMARK(bench_fmt_var_len);

static void bench_string_view(benchmark::State& state) 
{
    for (auto _: state) {
        char buf[4] = {'1','2','3','4'};
        benchmark::DoNotOptimize(fmt::format("{}", fmt::string_view(buf, 4)));
    }
}
BENCHMARK(bench_string_view);

// result
bench_fmt_var_len                            121 ns          121 ns      5729701
bench_string_view                           18.2 ns         18.2 ns     37584339
```

**Comment by ououmania** [comment]
> > The runtime length is supported by `fmt::format` too
> > fmt::format("{:.{}}", buffer, len);
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please see http://cppformat.github.io/2.0.0/syntax.html for more details.
> 
> I find one interesting thing. Use fmt::string_view has the same effect of this and higher performance.
> 
> ```
> static void bench_fmt_var_len(benchmark::State& state) 
> {
>     for (auto _: state) {
>         char buf[4] = {'1','2','3','4'};
>         benchmark::DoNotOptimize(fmt::format("{:.{}}", buf, 4));
>     }
> }
> BENCHMARK(bench_fmt_var_len);
> 
> static void bench_string_view(benchmark::State& state) 
> {
>     for (auto _: state) {
>         char buf[4] = {'1','2','3','4'};
>         benchmark::DoNotOptimize(fmt::format("{}", fmt::string_view(buf, 4)));
>     }
> }
> BENCHMARK(bench_string_view);
> 
> // result
> bench_fmt_var_len                            121 ns          121 ns      5729701
> bench_string_view                           18.2 ns         18.2 ns     37584339
> ```
Many thanks!

**Comment by vitaut** [comment]
Note that precision doesn't have the same effect because it works with UTF-8 and now computes estimated width, while string_view works on code unit level (which might be OK in some cases).
