### ISSUE TITLE
fmt::print() does not honor locale?

### ISSUE THREAD

**Issue by rogerdahl** [cppformat/cppformat#305]
Thank you for cppformat. It's awesome.

Is it possible to get cppformat to honor the current locale?

    locale::global(locale("en_US.utf8"));
    cout.imbue(locale("en_US.utf8"));
    cout << "iostream: " << 1234567 << endl;
    fmt::print("cppformat: {}\n", 1234567);

    iostream: 1,234,567
    cppformat: 1234567

**Comment by vitaut** [comment]
Thanks for a nice feedback.

`fmt::print` and `fmt::format` follow Python [`str.format`](https://docs.python.org/2/library/string.html)'s conventions with the default integer format being locale-independent:

```python
>>> from locale import setlocale, LC_ALL
>>> '{}'.format(1234567)
'1234567'
>>> setlocale(LC_ALL, 'en_US.utf8')
'en_US.utf8'
>>> '{}'.format(1234567)
'1234567'
>>> '{:n}'.format(1234567)
'1,234,567'
```

I've implemented the `n` format specifier in https://github.com/cppformat/cppformat/commit/f68771abe4b536a15889477b428985125a8cc5f2 so this should work now:

```c++
  std::setlocale(LC_ALL, "en_US.utf8");
  fmt::print("cppformat: {:n}\n", 1234567);
```

**Comment by tearfur** [comment]
Hi @vitaut, sorry if I missed something, it seems like the `n` specifier is currently undocumented.

I'd be happy to create a PR for updating the documentation, but I'm not confident I can give a good enough description of it. So could you please add it in?

**Comment by vitaut** [comment]
The `n` specifier has been renamed to `L` per feedback from the C++ committee.

**Comment by tearfur** [comment]
Ah I see, thanks.
