### ISSUE TITLE
Provide examples of using WindowsError and SystemError in the docs

### ISSUE THREAD

**Issue by vitaut** [cppformat/cppformat#54]
> Provide 2-3 examples of real Windows error codes in the example so its usage makes sense and mention what happens if you enter a code that is not an official error code.

**Comment by vitaut** [comment]
Added examples, but still need to clarify what happens if you pass an invalid error code.

**Comment by vitaut** [comment]
Fixed in https://github.com/cppformat/cppformat/commit/326ade7698d8fce18034f346b5e04bb52cd9590c.

**Comment by vitaut** [comment]
Took me only 7 months to close this =)

**Comment by patlecat** [comment]
Cool :+1:
