### ISSUE TITLE
warnings under Xcode 6.1.1 (probably with -Weverything)

### ISSUE THREAD

**Issue by dixlorenz** [cppformat/cppformat#96]
commit  ba17cca432416c6df7c862fc38c4c7a5905d0bc7, 2/6/2015:

format.h:
Unknown Command Tag Name:
line #142: /rst
line #164: \endrst
line #1567: out.write("Current point:\n");
the last one ist about "\n"; this might well be an Xcode bug

format.cpp:
Semantic issue, 'return' will never be executed
line #254, line #276
these returns are after an unconditional FMT_THROW

warning: comparison of integers of different signs: 'const int' and 'std::size_t' (aka 'unsigned long')
line #628: if (spec.precision_ >= 0 && spec.precision_ < str_size)
spec.precision_ and str_size are the problem.

**Comment by dixlorenz** [comment]
one more: in Result visit(const Arg &arg) clang complains about the fallthrough in release mode and suggests inserting [[clang::fallthrough]]. This gives a warning in debug mode though, because after the assert(false) it is unreachable code.

**Comment by vitaut** [comment]
Reopening until the fallthrough warning is resolved.

**Comment by vitaut** [comment]
@dixlorenz Could you please check if the fix in branch [fallthrough](https://github.com/cppformat/cppformat/tree/fallthrough) resolves the fallthrough warning? I tried detecting the availability of `[[clang::fallthrough]]` based on clang version there (you might need to change `600` to your version in https://github.com/cppformat/cppformat/blob/fallthrough/format.h#L124 if it is lower).

**Comment by dixlorenz** [comment]
Almost perfect. It resolves the fallthrough warning, but in debug build I now get

warning: fallthrough annotation in unreachable code

because of the assert(false)... Somewhat interestingly (to me): this code

    default:
      assert(false);
      return FMT_DISPATCH(visit_int(arg.int_value));
    case Arg::INT:
      return FMT_DISPATCH(visit_int(arg.int_value));

does not give a warning about unreachable code (or any other).

That might be the easiest/cleanest solution. It does have the same semantics as the fallthrough and doesn't need macros, #ifdefs or rely on the compiler or its version at all.

**Comment by vitaut** [comment]
So does [this commit](https://github.com/cppformat/cppformat/commit/a92c179a6dfc5037d0c191ddfabb1c3fe12f1439) fixes the warnings? (I used your suggestion but simplified it a bit since there is no need to dispatch there.) If it works I'll merge it into master and remove the fallthrough attribute detection.
Thanks!

**Comment by dixlorenz** [comment]
That works perfectly, no warning, neither in debug or in release.

**Comment by vitaut** [comment]
Closing the issue via https://github.com/cppformat/cppformat/commit/04a21bbb2e8f6fd028b8f6bce098c7370b45e94b then. Thanks again for your help.
