### ISSUE TITLE
Support pluralisation rules

### ISSUE THREAD

**Issue by KindDragon** [cppformat/cppformat#99]
https://github.com/scottrippey/SmartFormat.NET/wiki#pluralisation

```cpp
auto result = fmt::format("There {0:is|are} {0} {0:item|items} remaining", items.size());
// Result: "There is 1 item remaining" or "There are 2 items remaining"
```

**Comment by vitaut** [comment]
Thanks a lot for the suggestion, but unfortunately this is out of scope of the current library. The purpose of this library is to provide formatting functions like `printf` or Python's `str.format`. However, localization library can probably be built on top of C++ Format reusing some of its infrastructure in a similar way as it is done in a logging library, [spdlog](https://github.com/gabime/spdlog).
